# Generated by silicon-crew soc-openroad. Keep this file in the design repo.
THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
PROJECT_ROOT := $(abspath $(THIS_DIR)/../../../..)
export DESIGN_NAME = uart
export DESIGN_NICKNAME = uart
export PLATFORM = nangate45

RTL_FILELIST := $(PROJECT_ROOT)/ip/digital/uart/de/run/rtl.f
export VERILOG_FILES := $(shell sed -n -e 's|^/project/xuanwu9000/user/silicon/vibe_soc/|$(PROJECT_ROOT)/|p' -e 's|^\$$SOC/|$(PROJECT_ROOT)/|p' $(RTL_FILELIST))

export SDC_FILE = $(THIS_DIR)/constraint.sdc
export ABC_AREA ?= 1
export CORE_UTILIZATION ?= 55
export TNS_END_PERCENT ?= 100
export SYNTH_REPEATABLE_BUILD ?= 1
export PLACE_DENSITY_LB_ADDON ?= 0.20
export PDN_TCL ?= $(PLATFORM_DIR)/grid_strategy-M1-M4-M7.tcl
