// OpenTitan common RTL fragment split from chip/top frozen order.
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_blanker.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subst_perm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_present.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_prince.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_count_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_count.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_mux2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pad_attr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pad_wrapper.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1r1w.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_2p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_rom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_gf_mult.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lfsr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_max_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_msb_extend.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_dom_and_2share.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_const.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_pad.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_32.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sum_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_util_pkg.sv
