// OpenTitan common RTL fragment split from chip/top frozen order.
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_double_lfsr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_inv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_leading_one_ppc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_mux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_check.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1p_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1r1w_async_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_rom_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_trivium_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_trivium.sv
