# io_ss module
PROJECT_ROOT ?= $(shell cd ../.. && pwd -P)
MODULE_NAME   = io_ss
RTL_TOP      ?= io_top_top
USER_COMPILE_FLAGS += +incdir+$(PROJECT_ROOT)/chip/io_ss/de/rtl
include $(PROJECT_ROOT)/scripts/common.mk
