// timer - Programmable Timer IP
// Generated by soc-build skill

`timescale 1ns / 1ps

module timer (
    input  wire        clk,
    input  wire        rst_n,
    // APB interface
    input  wire        psel,
    input  wire        penable,
    input  wire        pwrite,
    input  wire [7:0]  paddr,
    input  wire [31:0] pwdata,
    output reg  [31:0] prdata,
    output reg         pready,
    // Timer outputs
    output reg         tick,       // periodic tick
    output reg         timeout     // one-shot timeout
);

    reg [31:0] load_val;
    reg [31:0] counter;
    reg        enable;
    reg        mode;       // 0=one-shot, 1=periodic
    reg        int_mask;

    // APB register interface
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            load_val <= 32'd1000;
            enable   <= 1'b0;
            mode     <= 1'b0;
            int_mask <= 1'b0;
            prdata   <= 32'b0;
            pready   <= 1'b0;
            tick     <= 1'b0;
            timeout  <= 1'b0;
        end else begin
            pready <= psel & penable;
            tick   <= 1'b0;
            timeout<= 1'b0;

            if (psel && penable && pwrite) begin
                case (paddr)
                    8'h00: load_val <= pwdata[31:0];
                    8'h04: enable   <= pwdata[0];
                    8'h08: mode     <= pwdata[0];
                    8'h0C: int_mask <= pwdata[0];
                    default: ;
                endcase
            end else if (psel && penable && !pwrite) begin
                case (paddr)
                    8'h00: prdata <= load_val;
                    8'h04: prdata <= {31'b0, enable};
                    8'h08: prdata <= {31'b0, mode};
                    8'h0C: prdata <= {31'b0, int_mask};
                    8'h10: prdata <= counter;
                    default: prdata <= 32'b0;
                endcase
            end

            // Counter logic
            if (enable) begin
                if (counter == 32'b0) begin
                    if (mode) begin
                        counter <= load_val;
                        tick <= ~int_mask;
                    end else begin
                        enable <= 1'b0;
                        timeout <= ~int_mask;
                    end
                end else begin
                    counter <= counter - 1'b1;
                end
            end else begin
                counter <= load_val;
            end
        end
    end

endmodule
