# Generated by silicon-crew soc-openroad. Keep this file in the design repo.
THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
PROJECT_ROOT := $(abspath $(THIS_DIR)/../../../..)
export DESIGN_NAME = stories260k
export DESIGN_NICKNAME = stories260k
export PLATFORM = nangate45

export VERILOG_FILES = \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k_mac.v \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k_spm.v \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k_regs.v \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k_sfu.v \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k_attn.v \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k_core.v \
  $(PROJECT_ROOT)/ip/digital/stories260k/de/rtl/stories260k.v

export SDC_FILE = $(THIS_DIR)/constraint.sdc
export ABC_AREA ?= 1
export TNS_END_PERCENT ?= 100
export SYNTH_REPEATABLE_BUILD ?= 1
# Target ~45% core utilization (auto die size from design area + macros).
# With full attn RTL, util50 + density0.55 left thin corridors near SPM and
# detail_place failed (DPL-0036 on ~13 wire* cells). Slightly looser floorplan.
export CORE_UTILIZATION = 45
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 10
# Fixed placer density (avoid PLACE_DENSITY_LB_ADDON; it overrides PLACE_DENSITY).
export PLACE_DENSITY = 0.50
export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT ?= 0
export CELL_PAD_IN_SITES_DETAIL_PLACEMENT ?= 0
export PDN_TCL ?= $(PLATFORM_DIR)/grid_strategy-M1-M4-M7.tcl

# stories260k macro handoff (SYNTHESIS blackbox SPM, real SRAM-area LEF)
export ADDITIONAL_LEFS += $(THIS_DIR)/stories260k_spm.lef
export ADDITIONAL_LIBS += $(THIS_DIR)/stories260k_spm.lib
# Manual pin+macro place (avoids RTLMP pin-location failure on this stub)
export PRE_MACRO_PLACE_TCL ?= $(THIS_DIR)/pre_macro_place.tcl
# GRT prep + ORFS 2024 compat (absolute paths for OpenROAD Tcl sourcing)
export STORIES260K_ORFS_COMPAT ?= $(PROJECT_ROOT)/pd/openroad/local/orfs_compat_2024.tcl
export PRE_GLOBAL_ROUTE_TCL ?= $(THIS_DIR)/pre_global_route.tcl
export MACRO_PLACE_HALO ?= 15 15
# Allow DPL to pull long-wire buffers off the SPM footprint after resize.
export DETAIL_PLACEMENT_ARGS ?= -max_displacement 2000
export SYNTH_HIERARCHICAL ?= 1
# Stub SPM has LEF/LIB only (no GDS); allow empty GDS merge for this cell
export GDS_ALLOW_EMPTY ?= stories260k_spm
export RECOVER_POWER ?= 0
