#!/usr/bin/env python3
"""YAML → sysmap fragment (.h) aligned with m2 sysmap header style."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import default_output_dir, fmt_hex, load_yml_model, stem_name


def generate_sysmap(model: dict) -> str:
    """Generate a module-level sysmap header.

    Prefer explicit parent_base + parent_offset when present:
        #define COMP_BASE (PARENT_BASE + 0x....)
    Else fall back to absolute base_address from YAML.
    """
    comp = model["component_name"]
    comp_upper = comp.upper()
    guard = f"__{comp_upper}_SYSMAP_H__"

    parent_base = model.get("parent_base")
    parent_offset = model.get("parent_offset")
    if parent_base is not None and parent_offset is not None:
        base_expr = f"({parent_base} + {fmt_hex(parent_offset)})"
    else:
        base_expr = model["base_address"]

    year = datetime.now().year
    lines = [
        "/*",
        f" * Copyright (C) {year}- SmartSens Technology (Shanghai) Co., Ltd.",
        " * All rights reserved.",
        " *",
        " * Generated by yml2reg (yml2sysmap) from YAML register description.",
        " * Module-level system map fragment; include from chip/top sysmap as needed.",
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"#define {comp_upper}_BASE                                            {base_expr}",
        f"#define {comp_upper}_RANGE                                           {model['range']}",
        f"#define {comp_upper}_PROTOCOL                                        /* {model['protocol']} */",
        "",
        "/* Per-register absolute addresses (BASE + offset) */",
    ]

    all_regs = list(model["registers"])
    for intp in model["interrupts"]:
        all_regs.extend(intp["registers"])
    all_regs.sort(key=lambda r: int(r["offset"], 0))

    if all_regs:
        max_name = max(len(r["name"].upper()) for r in all_regs)
        col = max_name + 16
        for reg in all_regs:
            name = reg["name"].upper()
            pad = " " * (col - len(name))
            lines.append(f"#define {name}{pad}({comp_upper}_BASE + {reg['offset']})")
    else:
        lines.append("/* (no registers) */")

    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Convert yml2reg YAML to sysmap fragment header")
    parser.add_argument("yaml_file", help="Input YAML register description")
    parser.add_argument("-o", "--output-dir", default="", help="Output directory (default: beside YAML)")
    args = parser.parse_args(argv)

    yaml_path = Path(args.yaml_file)
    model = load_yml_model(yaml_path)
    out_dir = default_output_dir(yaml_path, args.output_dir or None)
    out_path = out_dir / f"{stem_name(model).lower()}_sysmap.h"
    out_path.write_text(generate_sysmap(model), encoding="utf-8")
    print(f"Generated: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
