#!/usr/bin/env python3
"""YAML → C register header (layout aligned with xml_to_reg_c)."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import all_flat_registers, default_output_dir, hex_int, load_yml_model, stem_name


def _lpad(s: str, width: int) -> str:
    return s + " " * max(0, width - len(s))


def _generate_union_lines(reg: dict, prefix: str, fill_gaps: bool) -> list:
    lines = []
    reg_upper = reg["name"].upper()
    reg_lower = reg["name"].lower()

    lines.append(f"/* {reg_upper} : bits */")
    lines.append("typedef union {")
    lines.append("    struct {")

    fields = list(reg["fields"])
    if fill_gaps and fields:
        filled = []
        next_bit = 0
        for f in fields:
            if f["bit_offset"] > next_bit:
                gap = f["bit_offset"] - next_bit
                filled.append(
                    {
                        "name": f"reserved_{next_bit}_{f['bit_offset'] - 1}",
                        "description": "",
                        "bit_offset": next_bit,
                        "bit_width": gap,
                        "access": "RSVD",
                    }
                )
            filled.append(f)
            next_bit = f["bit_offset"] + f["bit_width"]
        fields = filled

    max_name_len = max((len(f["name"]) for f in fields), default=0)
    max_width_len = max((len(str(f["bit_width"])) for f in fields), default=0)

    for f in fields:
        end_bit = f["bit_offset"] + f["bit_width"] - 1
        name_part = _lpad(f["name"], max_name_len)
        width_str = str(f["bit_width"])
        width_pad = " " * (max_width_len - len(width_str))
        if f["access"] == "RSVD":
            comment = f"/*{f['bit_offset']}:{end_bit} */"
        else:
            comment = (
                f"/*{f['bit_offset']}:{end_bit} access={f['access']}  "
                f"{reg['reset']} {f['description']}*/"
            )
        lines.append(
            f"        volatile uint32_t {name_part} : {width_pad}{width_str}; {comment}"
        )

    lines.append("    } bf;")
    lines.append("    volatile uint32_t dw;")
    lines.append(f"}}{prefix}{reg_lower}_t;")
    lines.append("")
    return lines


def _make_define_lines(regs: list, comp_upper: str) -> list:
    if not regs:
        return []
    lines = []
    max_define_name = max((len(r["name"].upper()) for r in regs), default=0)
    define_value_col = max_define_name + 16
    for reg in regs:
        reg_upper = reg["name"].upper()
        padding = " " * (define_value_col - len(reg_upper))
        lines.append(f"#define {reg_upper}{padding}({comp_upper}_BASE + {reg['offset']})")
    return lines


def generate_c_header(model: dict, header_guard: str | None = None, fill_gaps: bool = True) -> str:
    comp = model["component_name"]
    comp_upper = comp.upper()
    comp_lower = comp.lower()
    prefix = f"{comp_lower}_"

    if header_guard is None:
        header_guard = f"__{comp_upper}_H__"

    lines = []
    year = datetime.now().year
    lines.append("/*")
    lines.append(f" * Copyright (C) {year}- SmartSens Technology (Shanghai) Co., Ltd.")
    lines.append(" * All rights reserved.")
    lines.append(" *")
    lines.append(" * Generated by yml2reg (yml2reg_c) from YAML register description.")
    lines.append(" * Do not hand-edit; change the YAML and regenerate.")
    lines.append(" */")
    lines.append(f"#ifndef {header_guard}")
    lines.append(f"#define {header_guard}")
    lines.append("")
    lines.append('#include "m2_reg_base_def.h"')
    lines.append("")
    lines.append(f"#ifndef {comp_upper}_BASE")
    lines.append(f"#define {comp_upper}_BASE {model['base_address']}")
    lines.append("#endif")
    lines.append("")

    normal_regs = model["registers"]
    int_groups = model["interrupts"]

    if normal_regs:
        lines.append("/* Register Address Definitions */")
        lines.extend(_make_define_lines(normal_regs, comp_upper))
        lines.append("")

    for int_group in int_groups:
        int_name = int_group["name"]
        bit_offset = int_group["bit_offset"]
        lines.append(f"//interrupt: {int_name}")
        lines.append(
            f"//{int_name}_RAW/STAT/MASK/SET/CLR/MODE/POLAR: {int_name}({bit_offset}) begin"
        )
        lines.extend(_make_define_lines(int_group["registers"], comp_upper))
        lines.append(f"//{int_name}/////// end")
        lines.append("")

    lines.append("#ifndef ASSEMBLER")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    for reg in normal_regs:
        lines.extend(_generate_union_lines(reg, prefix, fill_gaps))

    for int_group in int_groups:
        int_name = int_group["name"]
        bit_offset = int_group["bit_offset"]
        lines.append(f"//interrupt: {int_name}")
        lines.append(
            f"//{int_name}_RAW/STAT/MASK/SET/CLR/MODE/POLAR: {int_name}({bit_offset}) begin"
        )
        for reg in int_group["registers"]:
            lines.extend(_generate_union_lines(reg, prefix, fill_gaps))
        lines.append(f"//{int_name}/////// end")
        lines.append("")

    all_regs = all_flat_registers(model)
    reg_bytes = max(1, int(model.get("width", 32)) // 8)

    if all_regs:
        max_reg_type = max(len(f"{prefix}{reg['name'].lower()}_t") for reg in all_regs)
        # also need width for reserved arrays naming
        lines.append("/* MMIO layout with reserved holes for sparse offsets */")
        lines.append("typedef struct {")
        cursor = 0
        reserved_idx = 0
        for reg in all_regs:
            off = hex_int(reg["offset"])
            if off < cursor:
                lines.append(
                    f"    /* WARNING: overlapping/out-of-order offset {reg['offset']} "
                    f"(cursor=0x{cursor:x}) */"
                )
            elif off > cursor:
                gap = off - cursor
                if gap % reg_bytes != 0:
                    lines.append(
                        f"    /* WARNING: gap 0x{cursor:x}..0x{off:x} not multiple of {reg_bytes} */"
                    )
                nwords = gap // reg_bytes
                if nwords > 0:
                    rname = f"reserved_{reserved_idx}_0x{cursor:x}_0x{off - reg_bytes:x}"
                    lines.append(
                        f"    volatile uint32_t {_lpad(rname, max(max_reg_type, len(rname)))}"
                        f" [{nwords}]; /* hole {gap} bytes */"
                    )
                    reserved_idx += 1
                cursor = off
            reg_lower = reg["name"].lower()
            type_name = f"{prefix}{reg_lower}_t"
            lines.append(
                f"    {_lpad(type_name, max_reg_type)} {reg_lower};"
                f" /* +{reg['offset']} */"
            )
            cursor = off + reg_bytes
        lines.append(f"}} {prefix}t;")
        lines.append("")
        lines.append(
            f"/* Optional: (({prefix}t *){comp_upper}_BASE)->ctrl.bf.enable = 1; */"
        )
        lines.append("")

    lines.append("#endif/* ASSEMBLER */")
    lines.append("")
    lines.append(f"#endif /* {header_guard} */")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Convert yml2reg YAML to C register header")
    parser.add_argument("yaml_file", help="Input YAML register description")
    parser.add_argument("-o", "--output-dir", default="", help="Output directory (default: beside YAML)")
    parser.add_argument("-g", "--guard", default="", help="Custom header-guard macro")
    parser.add_argument(
        "--no-fill-gaps",
        action="store_true",
        help="Do not insert reserved_* bit-fields for gaps",
    )
    args = parser.parse_args(argv)

    yaml_path = Path(args.yaml_file)
    model = load_yml_model(yaml_path)
    out_dir = default_output_dir(yaml_path, args.output_dir or None)
    out_path = out_dir / f"{stem_name(model).lower()}.h"
    guard = args.guard or None
    text = generate_c_header(model, header_guard=guard, fill_gaps=not args.no_fill_gaps)
    out_path.write_text(text, encoding="utf-8")
    print(f"Generated: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
