#!/usr/bin/env python3
"""YAML → register init helpers for SW/DV (rals_parser *_regs_init style)."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import all_flat_registers, default_output_dir, hex_int, load_yml_model, stem_name


def _writable(reg: dict) -> bool:
    acc = str(reg.get("access", "RW")).upper()
    if acc in ("RO", "RSVD"):
        return False
    # if all fields RO, skip
    fields = reg.get("fields") or []
    if fields and all(str(f.get("access", "RW")).upper() == "RO" for f in fields):
        return False
    return True


def _reset_word(reg: dict) -> int:
    return hex_int(reg.get("reset", 0))


def generate_sv_init(model: dict) -> str:
    name = stem_name(model)
    upper = name.upper()
    lower = name.lower()
    regs = [r for r in all_flat_registers(model) if _writable(r)]
    year = datetime.now().year
    lines = [
        f"// Generated by yml2reg (yml2regs_init) {year}",
        f"`ifndef __{upper}_REGS_INIT_SV__",
        f"`define __{upper}_REGS_INIT_SV__",
        "",
        f'`include "{lower}_regs_define.svh"',
        f'`include "{name}_ral.svh"',
        "",
        f"// Write software-visible reset defaults via UVM regmodel",
        f"task {lower}_regs_init(reg_{name} model);",
        "  uvm_status_e status;",
        "",
    ]
    for r in regs:
        rname = r["name"]
        rst = _reset_word(r)
        lines.append(f"  // {rname} @ {r['offset']} reset=0x{rst:x}")
        lines.append(f"  model.{rname}.write(status, 32'h{rst:x});")
    lines.append("")
    lines.append(f"endtask : {lower}_regs_init")
    lines.append("")
    lines.append(f"`endif // __{upper}_REGS_INIT_SV__")
    lines.append("")
    return "\n".join(lines)


def generate_c_init_h(model: dict) -> str:
    name = stem_name(model)
    upper = name.upper()
    lower = name.lower()
    year = datetime.now().year
    return "\n".join(
        [
            f"/* Generated by yml2reg (yml2regs_init) {year} */",
            f"#ifndef __{upper}_REGS_INIT_H__",
            f"#define __{upper}_REGS_INIT_H__",
            "",
            f'#include "{lower}_regs_define.h"',
            "",
            f"#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "",
            f"void {lower}_regs_init(void);",
            "",
            f"#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            f"#endif /* __{upper}_REGS_INIT_H__ */",
            "",
        ]
    )


def generate_c_init(model: dict) -> str:
    name = stem_name(model)
    lower = name.lower()
    regs = [r for r in all_flat_registers(model) if _writable(r)]
    year = datetime.now().year
    lines = [
        f"/* Generated by yml2reg (yml2regs_init) {year} */",
        f'#include "{lower}_regs_init.h"',
        "",
        f"static inline void {lower}_wr32(unsigned long addr, unsigned int val) {{",
        "    *(volatile unsigned int *)addr = val;",
        "}",
        "",
        f"void {lower}_regs_init(void) {{",
        "",
    ]
    for r in regs:
        rname = r["name"].upper()
        rst = _reset_word(r)
        lines.append(f"    /* {rname} @ {r['offset']} */")
        lines.append(f"    {lower}_wr32({rname}, 0x{rst:x}u);")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate regs_init helpers from YAML")
    parser.add_argument("yaml_file")
    parser.add_argument("-o", "--output-dir", default="")
    args = parser.parse_args(argv)

    yaml_path = Path(args.yaml_file)
    model = load_yml_model(yaml_path)
    out_dir = default_output_dir(yaml_path, args.output_dir or None)
    lower = stem_name(model).lower()
    paths = [
        (out_dir / f"{lower}_regs_init.sv", generate_sv_init(model)),
        (out_dir / f"{lower}_regs_init.h", generate_c_init_h(model)),
        (out_dir / f"{lower}_regs_init.c", generate_c_init(model)),
    ]
    for p, text in paths:
        p.write_text(text, encoding="utf-8")
        print(f"Generated: {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
