#!/usr/bin/env python3
"""Generate lightweight UVM reg2bus adapter stubs (APB/AHB/DAB).

These are project-integration templates: item types are generic enough to
compile once the project provides matching sequence_item classes, or the
user can replace the item type names.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import default_output_dir, load_yml_model, stem_name


def generate_adapters(model: dict | None = None) -> str:
    year = datetime.now().year
    tag = stem_name(model) if model else "YML2REG"
    return f"""// Generated by yml2reg (yml2bus_adapters) {year}
// Module context: {tag}
// Templates — wire to your project's bus sequence items / sequencers.
`ifndef __YML2REG_BUS_ADAPTERS_SVH__
`define __YML2REG_BUS_ADAPTERS_SVH__

// ---------------------------------------------------------------------------
// APB adapter
// ---------------------------------------------------------------------------
class reg2apb_adapter extends uvm_reg_adapter;
  `uvm_object_utils(reg2apb_adapter)

  function new(string name = "reg2apb_adapter");
    super.new(name);
    supports_byte_enable = 0;
    provides_responses   = 1;
  endfunction

  virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);
    // Replace apb_seq_item with your project item type.
    apb_seq_item item = apb_seq_item::type_id::create("apb_item");
    item.addr  = rw.addr;
    item.write = (rw.kind == UVM_WRITE);
    item.data  = rw.data;
    return item;
  endfunction

  virtual function void bus2reg(uvm_sequence_item bus_item, ref uvm_reg_bus_op rw);
    apb_seq_item item;
    if (!$cast(item, bus_item)) begin
      `uvm_fatal("ADAPT", "bus_item is not apb_seq_item")
    end
    rw.addr   = item.addr;
    rw.data   = item.data;
    rw.kind   = item.write ? UVM_WRITE : UVM_READ;
    rw.status = UVM_IS_OK;
  endfunction
endclass : reg2apb_adapter

// ---------------------------------------------------------------------------
// AHB adapter
// ---------------------------------------------------------------------------
class reg2ahb_adapter extends uvm_reg_adapter;
  `uvm_object_utils(reg2ahb_adapter)

  function new(string name = "reg2ahb_adapter");
    super.new(name);
    supports_byte_enable = 0;
    provides_responses   = 1;
  endfunction

  virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);
    ahb_seq_item item = ahb_seq_item::type_id::create("ahb_item");
    item.addr  = rw.addr;
    item.write = (rw.kind == UVM_WRITE);
    item.data  = rw.data;
    item.size  = 2; // word
    return item;
  endfunction

  virtual function void bus2reg(uvm_sequence_item bus_item, ref uvm_reg_bus_op rw);
    ahb_seq_item item;
    if (!$cast(item, bus_item)) begin
      `uvm_fatal("ADAPT", "bus_item is not ahb_seq_item")
    end
    rw.addr   = item.addr;
    rw.data   = item.data;
    rw.kind   = item.write ? UVM_WRITE : UVM_READ;
    rw.status = UVM_IS_OK;
  endfunction
endclass : reg2ahb_adapter

// ---------------------------------------------------------------------------
// DAB adapter
// ---------------------------------------------------------------------------
class reg2dab_adapter extends uvm_reg_adapter;
  `uvm_object_utils(reg2dab_adapter)

  function new(string name = "reg2dab_adapter");
    super.new(name);
    supports_byte_enable = 0;
    provides_responses   = 1;
  endfunction

  virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);
    dab_seq_item item = dab_seq_item::type_id::create("dab_item");
    item.addr  = rw.addr;
    item.write = (rw.kind == UVM_WRITE);
    item.data  = rw.data;
    return item;
  endfunction

  virtual function void bus2reg(uvm_sequence_item bus_item, ref uvm_reg_bus_op rw);
    dab_seq_item item;
    if (!$cast(item, bus_item)) begin
      `uvm_fatal("ADAPT", "bus_item is not dab_seq_item")
    end
    rw.addr   = item.addr;
    rw.data   = item.data;
    rw.kind   = item.write ? UVM_WRITE : UVM_READ;
    rw.status = UVM_IS_OK;
  endfunction
endclass : reg2dab_adapter

`endif // __YML2REG_BUS_ADAPTERS_SVH__
"""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate UVM bus adapter stubs")
    parser.add_argument("yaml_file", nargs="?", default="")
    parser.add_argument("-o", "--output-dir", default="")
    args = parser.parse_args(argv)

    model = None
    out_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else Path(".")
    if args.yaml_file:
        yaml_path = Path(args.yaml_file)
        model = load_yml_model(yaml_path)
        out_dir = default_output_dir(yaml_path, args.output_dir or None)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "yml2reg_bus_adapters.svh"
    out_path.write_text(generate_adapters(model), encoding="utf-8")
    print(f"Generated: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
