#!/usr/bin/env python3
"""YAML top (multi-block) → chip-level UVM reg block.

Top YAML::

  name: SOC_TOP
  type: top
  base_address: 0x0
  protocol: apb
  coverage: false
  blocks:
    - yaml: demo_docs.yml
      base_address: 0x1000
      instance: u_sys_ctrl
      hdl_path: tb.dut.u_sys_ctrl
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import default_output_dir, hex_int, load_top_model, stem_name
from yml2uvm_ral import generate_uvm_ral


def _sv_hex(value) -> str:
    return f"32'h{hex_int(value):x}"


def generate_top_ral(top: dict) -> str:
    name = stem_name(top)
    base = _sv_hex(top.get("base_address", 0))
    protocol = str(top.get("protocol", "apb")).lower()
    coverage = "UVM_CVR_ALL" if top.get("coverage") else "UVM_NO_COVERAGE"
    year = datetime.now().year
    blocks = top.get("blocks") or []

    lines = [
        f"// Generated by yml2reg (yml2uvm_ral_top) {year}",
        f"// Multi-block top RAL for {name}",
        f"`ifndef __{name}_RAL_TOP_SVH__",
        f"`define __{name}_RAL_TOP_SVH__",
        "",
    ]
    for b in blocks:
        lines.append(f'`include "{stem_name(b)}_ral.svh"')
    lines.append("")
    lines.append(f"class reg_{name} extends uvm_reg_block;")
    for b in blocks:
        bname = stem_name(b)
        inst = b.get("instance", bname.lower())
        lines.append(f"  reg_{bname} {inst};")
    lines.append("")
    lines.append("  uvm_reg_map apb_map;")
    lines.append("  uvm_reg_map ahb_map;")
    lines.append("  uvm_reg_map dab_map;")
    lines.append(f"  int {name}_BASE;")
    lines.append("")
    lines.append(
        f'  function new(string name = "{name}", int base_address = {base});'
    )
    lines.append(f"    super.new(name, {coverage});")
    lines.append(f"    this.{name}_BASE = base_address;")
    lines.append("    this.build();")
    lines.append("    this.lock_model();")
    lines.append("    this.reset();")
    lines.append("  endfunction : new")
    lines.append("")
    lines.append("  virtual function void build();")
    for b in blocks:
        bname = stem_name(b)
        inst = b.get("instance", bname.lower())
        bbase = _sv_hex(b.get("base_address", 0))
        lines.append(
            f'    {inst} = reg_{bname}::type_id::create("{inst}",, get_full_name());'
        )
        # child not top: is_top_blk=0 then build manually
        lines.append(f"    // child base {bbase}")
        lines.append(f"    {inst}.{bname}_BASE = {bbase};")
        lines.append(f'    {inst}.configure(this, "{inst}");')
        lines.append(f"    {inst}.build();")
        lines.append(f"    {inst}.lock_model();")
        lines.append("")
    lines.append(
        f'    apb_map = create_map("apb_map", {name}_BASE, 4, UVM_LITTLE_ENDIAN);'
    )
    for b in blocks:
        bname = stem_name(b)
        inst = b.get("instance", bname.lower())
        bbase = _sv_hex(b.get("base_address", 0))
        lines.append(f"    apb_map.add_submap({inst}.apb_map, {bbase});")
    lines.append("")
    lines.append(
        f'    ahb_map = create_map("ahb_map", {name}_BASE, 4, UVM_LITTLE_ENDIAN);'
    )
    for b in blocks:
        bname = stem_name(b)
        inst = b.get("instance", bname.lower())
        bbase = _sv_hex(b.get("base_address", 0))
        lines.append(f"    ahb_map.add_submap({inst}.ahb_map, {bbase});")
    lines.append("")
    lines.append(
        f'    dab_map = create_map("dab_map", {name}_BASE, 4, UVM_LITTLE_ENDIAN);'
    )
    for b in blocks:
        bname = stem_name(b)
        inst = b.get("instance", bname.lower())
        bbase = _sv_hex(b.get("base_address", 0))
        lines.append(f"    dab_map.add_submap({inst}.dab_map, {bbase});")
    lines.append("")
    if protocol == "ahb":
        lines.append("    default_map = ahb_map;")
    elif protocol == "dab":
        lines.append("    default_map = dab_map;")
    else:
        lines.append("    default_map = apb_map;")
    lines.append("  endfunction : build")
    lines.append("")
    lines.append("  virtual function void connect(uvm_sequencer_base sqr);")
    for b in blocks:
        inst = b.get("instance", stem_name(b).lower())
        lines.append(f"    {inst}.default_map = this.default_map;")
        lines.append(f"    {inst}.connect(sqr);")
    lines.append("  endfunction : connect")
    lines.append("")
    lines.append(f"  `uvm_object_utils(reg_{name})")
    lines.append(f"endclass : reg_{name}")
    lines.append("")
    lines.append(f"`endif // __{name}_RAL_TOP_SVH__")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate multi-block top UVM RAL")
    parser.add_argument("yaml_file", help="Top YAML with blocks:[]")
    parser.add_argument("-o", "--output-dir", default="")
    parser.add_argument(
        "--emit-children",
        action="store_true",
        help="Also emit each child block *_ral.svh into output_dir",
    )
    args = parser.parse_args(argv)

    yaml_path = Path(args.yaml_file)
    top = load_top_model(yaml_path)
    out_dir = default_output_dir(yaml_path, args.output_dir or None)

    if args.emit_children:
        for b in top["blocks"]:
            child_path = out_dir / f"{stem_name(b)}_ral.svh"
            child_path.write_text(generate_uvm_ral(b), encoding="utf-8")
            print(f"Generated: {child_path}")

    out_path = out_dir / f"{stem_name(top)}_ral_top.svh"
    out_path.write_text(generate_top_ral(top), encoding="utf-8")
    print(f"Generated: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
