#!/usr/bin/env python3
"""YAML → regs_*_ral_lib.svh (extends UVM block + config task), rals REGH style."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import all_flat_registers, default_output_dir, hex_int, load_yml_model, stem_name


def generate_ral_lib(model: dict) -> str:
    name = stem_name(model)
    lower = name.lower()
    year = datetime.now().year
    regs = all_flat_registers(model)

    lines = [
        f"// Generated by yml2reg (yml2ral_lib) {year}",
        f"`ifndef __{name}_REG_RAL_LIB_SVH__",
        f"`define __{name}_REG_RAL_LIB_SVH__",
        "",
        f'`include "{name}_ral.svh"',
        "",
        f"// Thin wrapper class used by project sequences (rals_parser REGH style)",
        f"class regs_{name} extends reg_{name};",
        "",
        f'  function new(string name = "regs_{name}", bit is_top_blk = 1, int base_address = 32\'h{hex_int(model.get("base_address", 0)):x});',
        "    super.new(name, is_top_blk, base_address);",
        "  endfunction : new",
        "",
        "  // Convenience: mirror all regs (front-door)",
        "  task mirror_all(uvm_path_e path = UVM_FRONTDOOR);",
        "    uvm_status_e status;",
    ]
    for r in regs:
        lines.append(f"    this.{r['name']}.mirror(status, UVM_CHECK, path);")
    lines.append("  endtask : mirror_all")
    lines.append("")
    lines.append("  // Convenience: write known reset image")
    lines.append("  task write_reset_image();")
    lines.append("    uvm_status_e status;")
    for r in regs:
        acc = str(r.get("access", "RW")).upper()
        if acc == "RO":
            continue
        fields = r.get("fields") or []
        if fields and all(str(f.get("access", "RW")).upper() == "RO" for f in fields):
            continue
        lines.append(
            f"    this.{r['name']}.write(status, 32'h{hex_int(r.get('reset', 0)):x});"
        )
    lines.append("  endtask : write_reset_image")
    lines.append("")
    lines.append(f"  `uvm_object_utils(regs_{name})")
    lines.append(f"endclass : regs_{name}")
    lines.append("")
    lines.append(
        f"// Optional config task: apply associative array cfg_data[frame][reg_name] = value"
    )
    lines.append(
        f"task {lower}_reg_config(regs_{name} model, int frame_no, int start_frame_no, int cfg_data[int][string]);"
    )
    lines.append("  uvm_status_e status;")
    lines.append("  string key;")
    lines.append("  if (frame_no < start_frame_no) return;")
    lines.append("  if (!cfg_data.exists(frame_no)) return;")
    lines.append("  if (cfg_data[frame_no].first(key)) begin")
    lines.append("    do begin")
    for r in regs:
        rname = r["name"]
        lines.append(f'      if (key == "{rname}" || key == "{rname.upper()}")')
        lines.append(
            f"        model.{rname}.write(status, cfg_data[frame_no][key]);"
        )
    lines.append("    end while (cfg_data[frame_no].next(key));")
    lines.append("  end")
    lines.append(f"endtask : {lower}_reg_config")
    lines.append("")
    lines.append(f"`endif // __{name}_REG_RAL_LIB_SVH__")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate regs_*_ral_lib.svh from YAML")
    parser.add_argument("yaml_file")
    parser.add_argument("-o", "--output-dir", default="")
    args = parser.parse_args(argv)

    yaml_path = Path(args.yaml_file)
    model = load_yml_model(yaml_path)
    out_dir = default_output_dir(yaml_path, args.output_dir or None)
    out_path = out_dir / f"{stem_name(model)}_regs_ral_lib.svh"
    out_path.write_text(generate_ral_lib(model), encoding="utf-8")
    print(f"Generated: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
