#!/usr/bin/env python3
"""YAML → verification define headers (C + SystemVerilog).

Produces rals_parser-style:
  - <name>_regs_define.h
  - <name>_regs_define.svh

Address macros only (BASE + offset), including expanded interrupt banks.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

from yml_model import default_output_dir, load_yml_model, stem_name


def _hex_int(v) -> int:
    if v is None:
        return 0
    if isinstance(v, int):
        return v
    return int(str(v).strip(), 0)


def _all_regs(model: dict) -> list:
    regs = list(model["registers"])
    for intp in model["interrupts"]:
        regs.extend(intp["registers"])
    regs.sort(key=lambda r: _hex_int(r["offset"]))
    return regs


def generate_c_define(model: dict) -> str:
    name = stem_name(model)
    upper = name.upper()
    lower = name.lower()
    base = model.get("base_address", "0x0")
    year = datetime.now().year
    lines = [
        f"/* Generated by yml2reg (yml2sv_define) {year} */",
        f"#ifndef __{upper}_REGS_DEFINE_H__",
        f"#define __{upper}_REGS_DEFINE_H__",
        "",
        '#include "sysmap.h"',
        "",
        f"#ifndef {upper}_BASE",
        f"#define {upper}_BASE {base}",
        "#endif",
        "",
    ]
    regs = _all_regs(model)
    max_len = max((len(r["name"].upper()) for r in regs), default=8)
    col = max_len + 8
    for r in regs:
        rn = r["name"].upper()
        pad = " " * (col - len(rn))
        lines.append(f"#define {rn}{pad}({upper}_BASE + {r['offset']})")
    lines.append("")
    lines.append(f"#endif /* __{upper}_REGS_DEFINE_H__ */")
    lines.append("")
    return "\n".join(lines)


def generate_sv_define(model: dict) -> str:
    name = stem_name(model)
    upper = name.upper()
    base = model.get("base_address", "0x0")
    year = datetime.now().year
    lines = [
        f"// Generated by yml2reg (yml2sv_define) {year}",
        f"`ifndef __{upper}_REGS_DEFINE_SVH__",
        f"`define __{upper}_REGS_DEFINE_SVH__",
        "",
        "// Optional: `include \"sysmap.svh\"",
        "",
        f"`ifndef {upper}_BASE",
        f"`define {upper}_BASE {base}",
        "`endif",
        "",
    ]
    regs = _all_regs(model)
    max_len = max((len(r["name"].upper()) for r in regs), default=8)
    col = max_len + 8
    for r in regs:
        rn = r["name"].upper()
        pad = " " * (col - len(rn))
        lines.append(f"`define {rn}{pad}({upper}_BASE + {r['offset']})")
    lines.append("")
    lines.append(f"`endif // __{upper}_REGS_DEFINE_SVH__")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate DV define headers from YAML")
    parser.add_argument("yaml_file")
    parser.add_argument("-o", "--output-dir", default="")
    args = parser.parse_args(argv)

    yaml_path = Path(args.yaml_file)
    model = load_yml_model(yaml_path)
    out_dir = default_output_dir(yaml_path, args.output_dir or None)
    lower = stem_name(model).lower()
    c_path = out_dir / f"{lower}_regs_define.h"
    sv_path = out_dir / f"{lower}_regs_define.svh"
    c_path.write_text(generate_c_define(model), encoding="utf-8")
    sv_path.write_text(generate_sv_define(model), encoding="utf-8")
    print(f"Generated: {c_path}")
    print(f"Generated: {sv_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
