// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// FPV CSR read and write assertions auto-generated by `reggen` containing data structure
// Do Not Edit directly
// TODO: This automation currently only support register without HW write access
`include "prim_assert.sv"
`ifdef UVM
  `include "uvm_macros.svh"
`endif

 // An upwards hierarchical reference that starts at the type of the IP block. This will correctly
 // find the block, as long as the assertion module is bound into the block (rather than sitting
 // outside of it) in the testbench.
`define REGWEN_PATH clkmgr.u_reg

// Block: clkmgr
module clkmgr_csr_assert_fpv import tlul_pkg::*;
    import top_pkg::*;(
  input clk_i,
  input rst_ni,

  // tile link ports
  input tl_h2d_t h2d,
  input tl_d2h_t d2h
);

  import prim_mubi_pkg::*;
`ifdef UVM
  import uvm_pkg::*;
`endif

// Currently FPV csr assertion only support HRO registers.
`ifndef VERILATOR
`ifndef SYNTHESIS

  logic oob_addr_err;

  typedef struct packed {
    logic [TL_DW-1:0] wr_data;
    logic [TL_AW-1:0] addr;
    logic             wr_pending;
    logic             rd_pending;
  } pend_item_t;

  bit disable_sva;

  // mask register to convert byte to bit
  logic [TL_DW-1:0] a_mask_bit;

  assign a_mask_bit[7:0]   = h2d.a_mask[0] ? '1 : '0;
  assign a_mask_bit[15:8]  = h2d.a_mask[1] ? '1 : '0;
  assign a_mask_bit[23:16] = h2d.a_mask[2] ? '1 : '0;
  assign a_mask_bit[31:24] = h2d.a_mask[3] ? '1 : '0;

  // An index used for regwen, access_policy and exp_vals. These arrays all have one element per HRO
  // register, plus an extra dummy entry to represent "non-HRO registers" (avoiding out-of-bounds
  // accesses).
  bit [2:0] hro_idx;
  bit [6:0] normalized_addr;

  `ifdef FPV_ON
    // For FPV, we restrict the pend_trans array by giving its size a smaller upper bound. This
    // reduces the FPV runtime dramatically.
    localparam int PendTransLen = 11;

    // These two assumptions bound h2d.a_source and d2h.d_source for FPV because they are used as
    // indices for the array.
    `ASSUME_FPV(TlulSourceA_M, h2d.a_source >=  0 && h2d.a_source < PendTransLen, clk_i, !rst_ni)
    `ASSUME_FPV(TlulSourceD_M, d2h.d_source >=  0 && d2h.d_source < PendTransLen, clk_i, !rst_ni)
  `else
    localparam int PendTransLen = 2**TL_AIW;
  `endif

  pend_item_t [PendTransLen-1:0] pend_trans;

  // Indexes of pend_trans have a width that depends on the size of the array. These lines extract
  // just the bottom bits (so that the widths match).
  //
  // When in FPV mode, the TlulSource*_M assumptions above ensure that we aren't dropping any
  // nonzero bits. When not in FPV mode, this is a no-op: the a_source and d_source values are of
  // width TL_AIW and we extract that many bits.
  localparam int PendTransIdxWidth = $clog2(PendTransLen);
  logic [PendTransIdxWidth-1:0] a_source_idx, d_source_idx;

  assign a_source_idx = h2d.a_source[PendTransIdxWidth-1:0];
  assign d_source_idx = d2h.d_source[PendTransIdxWidth-1:0];

  // Map register address with hro_idx in exp_vals array.
  always_comb begin: decode_hro_addr_to_idx
    unique case (pend_trans[d_source_idx].addr)
      0: hro_idx = 0;
      4: hro_idx = 1;
      8: hro_idx = 2;
      16: hro_idx = 3;
      20: hro_idx = 4;
      24: hro_idx = 5;
      28: hro_idx = 6;
      // If the register is not a HRO register, the write data will all update to this default idx.
      default: hro_idx = 7;
    endcase
  end

  // store internal expected values for HW ReadOnly registers
  logic [TL_DW-1:0] exp_vals[8];

  // Word-align the incoming TLUL a_address to obtain the normalized address.
  assign normalized_addr = {h2d.a_address[6:2], 2'b0};

  // Assign regwen to registers. If the register does not have regwen, it will default to value 1.
  logic [7:0] regwen;
  assign regwen[0] = 1;
  assign regwen[1] = 1;
  assign regwen[2] = `REGWEN_PATH.extclk_ctrl_regwen_qs;
  assign regwen[3] = 1;
  assign regwen[4] = `REGWEN_PATH.jitter_regwen_qs;
  assign regwen[5] = 1;
  assign regwen[6] = 1;
  assign regwen[7] = 1;

  // Types of REGWEN supported.
  typedef enum {
    NotRegwen,
    MuBi4Regwen,
    MuBi8Regwen,
    MuBi12Regwen,
    MuBi16Regwen
  } regwen_type_t;

  // The REGWEN type of each register, if any.
  regwen_type_t regwen_types[7];
      assign regwen_types[0] = NotRegwen;
      assign regwen_types[1] = NotRegwen;
      assign regwen_types[2] = MuBi4Regwen;
      assign regwen_types[3] = NotRegwen;
      assign regwen_types[4] = MuBi4Regwen;
      assign regwen_types[5] = NotRegwen;
      assign regwen_types[6] = NotRegwen;

  typedef enum bit {
    FpvDefault,
    FpvRw0c
  } fpv_reg_access_e;
  fpv_reg_access_e access_policy [8];

  // for write HRO registers, store the write data into exp_vals
  always_ff @(negedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
       oob_addr_err <= 1'b0;
       pend_trans <= '0;
       exp_vals[0] <= 'h0;
       access_policy[0] <= FpvDefault;
       exp_vals[1] <= 'h1;
       access_policy[1] <= FpvRw0c;
       exp_vals[2] <= 'h99;
       access_policy[2] <= FpvDefault;
       exp_vals[3] <= 'h1;
       access_policy[3] <= FpvRw0c;
       exp_vals[4] <= 'h9;
       access_policy[4] <= FpvDefault;
       exp_vals[5] <= 'hf;
       access_policy[5] <= FpvDefault;
       exp_vals[6] <= 'hf;
       access_policy[6] <= FpvDefault;
       exp_vals[7] <= 'h0;
       access_policy[7] <= FpvDefault;
    end else begin
      oob_addr_err <= 1'b0;
      if (h2d.a_valid && d2h.a_ready) begin
        if ((normalized_addr inside {[0:84]})
           ) begin
          pend_trans[a_source_idx].addr <= normalized_addr;
          if (h2d.a_opcode inside {PutFullData, PutPartialData}) begin
            pend_trans[a_source_idx].wr_data <= h2d.a_data & a_mask_bit;
            pend_trans[a_source_idx].wr_pending <= 1'b1;
          end else if (h2d.a_opcode == Get) begin
            pend_trans[a_source_idx].rd_pending <= 1'b1;
          end
        end else begin
          oob_addr_err <= 1'b1;
        end
      end
      if (d2h.d_valid) begin
        if (pend_trans[d_source_idx].wr_pending == 1) begin
          if (!d2h.d_error && regwen[hro_idx]) begin
            if (access_policy[hro_idx] == FpvRw0c) begin
              // Assume FpvWr0c policy only has one field that is wr0c.
              unique case (regwen_types[hro_idx])
                MuBi4Regwen:
                  exp_vals[hro_idx] <=
                    mubi4_and_hi(mubi4_t'(exp_vals[hro_idx][3:0]),
                                 mubi4_t'(pend_trans[d2h.d_source].wr_data[3:0]));
                MuBi8Regwen:
                  exp_vals[hro_idx] <=
                    mubi8_and_hi(mubi8_t'(exp_vals[hro_idx][7:0]),
                                 mubi8_t'(pend_trans[d2h.d_source].wr_data[7:0]));
                MuBi12Regwen:
                  exp_vals[hro_idx] <=
                    mubi12_and_hi(mubi12_t'(exp_vals[hro_idx][11:0]),
                                  mubi12_t'(pend_trans[d2h.d_source].wr_data[11:0]));
                MuBi16Regwen:
                  exp_vals[hro_idx] <=
                    mubi16_and_hi(mubi16_t'(exp_vals[hro_idx][15:0]),
                                  mubi16_t'(pend_trans[d2h.d_source].wr_data[15:0]));
                default:
                  exp_vals[hro_idx] <=
                    exp_vals[hro_idx][0] ? pend_trans[d2h.d_source].wr_data : 0;
              endcase
            end else begin
              exp_vals[hro_idx] <= pend_trans[d_source_idx].wr_data;
            end
          end
          pend_trans[d_source_idx].wr_pending <= 1'b0;
        end
        if (h2d.d_ready && pend_trans[d_source_idx].rd_pending == 1) begin
          pend_trans[d_source_idx].rd_pending <= 1'b0;
        end
      end
    end
  end

  // for read HRO registers, assert read out values by access policy and exp_vals
  `ASSERT(extclk_ctrl_regwen_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 7'h4) |->
          (d2h.d_error ||
           (d2h.d_data & 'h1) ==
            (exp_vals[1] & 'h1)))
  `ASSERT(extclk_ctrl_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 7'h8) |->
          (d2h.d_error ||
           (d2h.d_data & 'hff) ==
            (exp_vals[2] & 'hff)))
  `ASSERT(jitter_regwen_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 7'h10) |->
          (d2h.d_error ||
           (d2h.d_data & 'h1) ==
            (exp_vals[3] & 'h1)))
  `ASSERT(jitter_enable_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 7'h14) |->
          (d2h.d_error ||
           (d2h.d_data & 'hf) ==
            (exp_vals[4] & 'hf)))
  `ASSERT(clk_enables_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 7'h18) |->
          (d2h.d_error ||
           (d2h.d_data & 'hf) ==
            (exp_vals[5] & 'hf)))
  `ASSERT(clk_hints_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 7'h1c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hf) ==
            (exp_vals[6] & 'hf)))

  `ASSERT(TlulOOBAddrErr_A, oob_addr_err |-> s_eventually(d2h.d_valid && d2h.d_error))

  `ifdef UVM
    initial forever begin
      bit csr_assert_en;
      uvm_config_db#(bit)::wait_modified(null, "%m", "csr_assert_en");
      if (!uvm_config_db#(bit)::get(null, "%m", "csr_assert_en", csr_assert_en)) begin
        `uvm_fatal("csr_assert", "Can't find csr_assert_en")
      end
      disable_sva = !csr_assert_en;
    end
  `endif

`endif
`endif
endmodule

`undef REGWEN_PATH
