// OpenTitan Earlgrey vendor simulation filelist for vibe_soc chip/top.
// Source order is frozen from the known-good FuseSoC top_earlgrey_chip_sim dependency graph.
// Source paths are project-owned RTL paths only: de/rtl/vendor/opentitan plus de/rtl/generated/opentitan_fusesoc.

+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_prince/crypto_dpi_prince
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/detail
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm/mixin
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm/detail/constants
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm/detail
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/gpiodpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/uartdpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/model
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_model
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_reg
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/csr_utils
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pattgen_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pwm_monitor
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/scoreboard
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_dmi_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_riscv_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_riscv_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/env/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/dv/aes_model_dpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/tests
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_bkdr_util
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/autogen
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tests
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tb
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/autogen

$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/jtag_id_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_present/crypto_dpi_present/crypto_dpi_present.cc
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_present/crypto_dpi_present/crypto_dpi_present_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/digestpp_dpi.cc
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/digestpp_dpi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/gpiodpi/gpiodpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/uartdpi/uartdpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi_stream.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi_test.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_crc.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_monitor.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_transfer.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_utils.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/gpiodpi/gpiodpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/uartdpi/uartdpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/pins_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/rst_shadowed_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/dv/env/spi_host_env_cfg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_main/dv/autogen/xbar_main_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_peri/dv/autogen/xbar_peri_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/usb20_agent/usb20_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/usb20_agent/usb20_usbdpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/tb/xbar_macros.svh
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/top_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_ack_sm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_main_sm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/jtag_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otp_macro/rtl/otp_macro_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/model/crypto.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/model/aes.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_cipher_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_crc32.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_and2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_gating.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_const.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_const_sec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_no_rst.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_inv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_2p_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_rom_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_usb_diff_rx.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_xnor2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_xor2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_22_16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_22_16_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_28_22_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_28_22_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_39_32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_39_32_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_64_57_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_64_57_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_72_64_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_72_64_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/top_earlgrey_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/common_ifs_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/clk_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/clk_rst_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_prince/crypto_dpi_prince/crypto_dpi_prince.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_prince/crypto_dpi_prince/crypto_dpi_prince_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mgr_lib/pwrmgr_rstmgr_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/str_utils/str_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sw_test_status/sw_test_status_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sw_test_status/sw_test_status_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/scan_role_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_icache.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_tracer_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_tracer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_core_ibex/rtl/rv_core_ibex_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/bus_params_pkg/bus_params_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_blanker.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subst_perm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_present.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_prince.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_count_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_count.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_mux2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pad_attr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pad_wrapper.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1r1w.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_2p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_rom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_gf_mult.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lfsr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_max_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_msb_extend.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_dom_and_2share.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_const.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_pad.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_32.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sum_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/physical_pads.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/ibex_pmp_reset_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils/dv_test_status_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_model/mem_model_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sw_logger_if/sw_logger_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_double_lfsr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_inv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_leading_one_ppc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_mux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_check.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1p_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1r1w_async_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_rom_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_trivium_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_trivium.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mgr_lib/clkmgr_pwrmgr_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils/dv_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/testing/lc_ctrl_token_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_alu.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_branch_predict.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_compressed_decoder.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_cs_registers.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_csr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_counter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_decoder.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_ex_block.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_fetch_fifo.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_id_stage.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_if_stage.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_load_store_unit.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_multdiv_fast.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_multdiv_slow.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_prefetch_buffer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_pmp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_wb_stage.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_dummy_instr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_arbiter_fixed.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_arbiter_ppc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_arbiter_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_arbiter_tree_dup.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_diff_decode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_edge_detector.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_fifo_async_simple.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_fifo_async.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_fifo_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_div.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_rst_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_multibit_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1p_scr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_reg_we_check.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subreg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_reg_cdc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_reg_cdc_arb.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subreg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subreg_arb.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subreg_ext.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subreg_shadow.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/padring.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_data_integ_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_data_integ_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_agent/dv_base_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_reg/dv_base_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_aon_cg_en_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_cg_en_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_div_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_extclk_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_gated_clock_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_lost_calib_ctrl_en_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_lost_calib_regwen_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_trans_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_clock_enables_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_rstreqs_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_pwrmgr_csr_assert_0/pwrmgr_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_ff.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_fpga.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_latch.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_lockstep.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_alert_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_alert_receiver.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_alert_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_esc_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_esc_receiver.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_esc_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lc_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lc_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lc_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_racl_error_arb.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_fifo_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_fifo_async.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_assert.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_err.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_assert_multiple.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/csr_utils/csr_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_onehot_check_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_count_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_double_lfsr_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_singleton_fifo_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_onehot_check_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_count_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_sparse_fsm_flop_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_double_lfsr_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_singleton_fifo_bind.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_dv_chip_ral_pkg_0/chip_ral_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_sec_cm_checker_assert.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_clkmgr_csr_assert_0/clkmgr_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_top_specific_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_target.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otp_macro/rtl/otp_macro_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otp_macro/rtl/otp_macro_prim_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otp_macro/rtl/otp_macro.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/rtl/sram_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/rtl/sram_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_clock_gating_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_hpc2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_hpc3.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sram_arbiter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_slicer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sync_reqack.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sync_reqack_data.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sync_slow_fast.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_keccak.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_packer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_packer_fifo.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_gate_gen.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_pulse_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_filter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_filter_ctr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_flop_x.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_intr_hw.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lc_or_hardened.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_host.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_sram_byte.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_sram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_lc_gate.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_request_loopback.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_err_resp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_socket_1n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_socket_m1.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/sram2tlul.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_lib/dv_lib_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sim_sram/tlul_sink.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sim_sram/sim_sram_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sim_sram/sim_sram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_top_specific_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_cnsty_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_consts_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_fs_nb_in_pe.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_fs_nb_out_pe.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_fs_nb_pe.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_fs_rx.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_fs_tx.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usb_fs_tx_mux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_edn_req.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_clock_meas.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_clock_timeout.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_racl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_sba.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_mem.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dmi_cdc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/pulp_riscv_dbg/src/dm_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/alert_esc_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/alert_esc_probe_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/alert_esc_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent/jtag_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent/jtag_mon_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent/jtag_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pattgen_agent/pattgen_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pattgen_agent/pattgen_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent/push_pull_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent/push_pull_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pwm_monitor/pwm_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pwm_monitor/pwm_monitor_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/scoreboard/scoreboard_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent/spi_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent/spi_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent/tl_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent/tl_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent/uart_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent/uart_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prim_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_dmi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/rtl/tlul_jtag_dtm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_base_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_mubi_cov_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_mubi_cov_wrapper.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_lc_tx_cov_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_dmi_agent/jtag_dmi_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_dmi_agent/jtag_rv_debugger_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flash.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/dv/env/lc_ctrl_dv_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/env/xbar_env_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_chan.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_por.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_crash_info.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_leaf_rst.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex_cfg_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex_addr_trans.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_intr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctrl_reg_shadowed.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctrl_gcm_reg_shadowed.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr_fsm_p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr_fsm_n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control_fsm_p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control_fsm_n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_reg_status.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sel_buf_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sub_bytes.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_lut.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_dom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_shift_rows.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_mix_columns.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_mix_single_column.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_key_expand.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_prng_clearing.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_prng_masking.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ghash.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_ack_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_main_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_fifo_sync_sram_adapter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_fifos.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_bus_monitor.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_controller_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_target_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_controller.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_decoder.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_predecode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_instruction_fetch.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_base.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_bignum.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_base_ff.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_bignum_ff.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_base_fpga.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_bignum_fpga.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_lsu.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_alu_base.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_alu_bignum.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mac_bignum_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mac_bignum.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mai.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mask_accelerator.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mod_result_selector.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_loop_controller.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_stack.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rnd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_sec_add.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_start_stop_control.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_adder.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_multiplier.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_shifter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_transposer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_scramble_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_chan.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_dbg_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_dmi_gate.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/timer_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/rv_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/sha3_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/keccak_round.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/keccak_2share.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/sha3pad.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/sha3.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_cmdparse.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_dpram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_readsram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_readbuffer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_readcmd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_passthrough.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_status.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_jedec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_addr_4b.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_fifo2sram_adapter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_csb_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_upload.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_tpm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_s2p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_p2s.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_cmd_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_shift_register.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_byte_select.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_byte_merge.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_command_queue.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_data_fifos.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_window.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/rtl/sram_ctrl_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/rtl/sram_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_autoblock.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_comboact.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_pin.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_keyintr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_detect.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_combo.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_ulp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_intr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/uart/rtl/uart_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/uart/rtl/uart_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/uart/rtl/uart_rx.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/uart/rtl/uart_tx.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/uart/rtl/uart_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/uart/rtl/uart.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_usbif.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_linkstate.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_iomux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_counter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_aon_wake.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/adc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/adc_ana.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vcaon_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_alert.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/aon_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/aon_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/io_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/io_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/sys_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/gfr_clk_mux2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_pulse_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/rng.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_dft.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_main/rtl/autogen/tl_main_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_peri/rtl/autogen/tl_peri_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_peri/rtl/autogen/xbar_peri.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/dv/aes_model_dpi/aes_model_dpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/dv/aes_model_dpi/aes_model_dpi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent/i2c_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/dv/sva/spi_host_data_stable_sva.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/dv/sva/spi_host_bind.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_spi_host_csr_assert_0/spi_host_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/tests/xbar_test_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_attrs_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_cascading_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_rst_en_track_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_sw_rst_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_wrap.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_lpg_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_class.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_esc_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_accu.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_byp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_clk_status.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_meas_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_root_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_trans.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_erase.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prog.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_rd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_arb.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_info_cfg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_region_cfg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp_data_region_sel.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buffers.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_prog.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_erase.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_scramble.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_wkup.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_jtag_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_jtag_breakout.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_strap_sampling.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_cdc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_slow_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_wake_info.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_main_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_state_db.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_cmd_stage.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_block_encrypt.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_ctr_drbg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_watermark_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_field_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_cntr_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_repcnts_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_enable_delay.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_bkdr_util/mem_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/testing/top_earlgrey_rnd_cnst_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_bind.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_rstmgr_csr_assert_0/rstmgr_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_cfg_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_data_en_state.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_err.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_input_checks.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_kmac_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_op_state_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_sideload_key.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_msgfifo.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_staterd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_app.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_entropy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_errchk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_dmi_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_counter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_mux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_scrambled_rom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/dv/env/sram_scrambler_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/dv/env/sram_ctrl_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_scrambler_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_ecc_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_scrmbl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_kdi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lci.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/dv/env/rom_ctrl_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/chip_common_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/chip_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/chip_env_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/alerts_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/ast_ext_clk_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/ast_supply_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/pwrmgr_low_power_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/rstmgr_cnsty_fault_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/flash_ctrl_host_gnt_fault_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/tb_dpi_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/top_earlgrey_error_injection_ifs_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/sva/clk_ctrl_and_main_pd_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/sva/top_earlgrey_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tests/chip_test_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tb/tb.sv
