// ============================================================================
// vibe_soc_top
// ============================================================================
// AUTO-GENERATED by soc_integrate.py
// Timestamp: 2026-05-02T11:16:26.788341
//
// DO NOT EDIT THIS FILE DIRECTLY.
// Modify sub-modules and re-run: soc_integrate.py integrate ...
// For manual connections, use assign statements in a separate file.
// ============================================================================

module vibe_soc_top (
    input         clk,
    input         rst_n,
    input  [7:0]  data_in,
    input         valid_in,
    input         psel,
    input         penable,
    input         pwrite,
    input  [7:0]  paddr,
    input  [31:0] pwdata,
    output [7:0]  core_data_out,
    output        core_valid_out,
    output [7:0]  bus_data_out,
    output        bus_valid_out,
    output [31:0] uart_prdata,
    output        uart_pready,
    input         uart_uart_rx,
    output        uart_uart_tx,
    output        uart_tx_ready,
    output        uart_rx_valid,
    output [7:0]  uart_rx_data,
    output        uart_irq,
    output [31:0] timer_prdata,
    output        timer_pready,
    output        timer_tick,
    output        timer_timeout
);

    core u_core (
        .clk       (clk),                 // input
        .rst_n     (rst_n),               // input
        .data_in   (data_in[7:0]),        // input
        .valid_in  (valid_in),            // input
        .data_out  (core_data_out[7:0]),  // output
        .valid_out (core_valid_out)       // output
    );

    bus u_bus (
        .clk       (clk),                // input
        .rst_n     (rst_n),              // input
        .data_in   (data_in[7:0]),       // input
        .valid_in  (valid_in),           // input
        .data_out  (bus_data_out[7:0]),  // output
        .valid_out (bus_valid_out)       // output
    );

    uart u_uart (
        .clk      (clk),                // input
        .rst_n    (rst_n),              // input
        .psel     (psel),               // input
        .penable  (penable),            // input
        .pwrite   (pwrite),             // input
        .paddr    (paddr[7:0]),         // input
        .pwdata   (pwdata[31:0]),       // input
        .prdata   (uart_prdata[31:0]),  // output
        .pready   (uart_pready),        // output
        .uart_rx  (uart_uart_rx),       // input
        .uart_tx  (uart_uart_tx),       // output
        .tx_ready (uart_tx_ready),      // output
        .rx_valid (uart_rx_valid),      // output
        .rx_data  (uart_rx_data[7:0]),  // output
        .irq      (uart_irq)            // output
    );

    timer u_timer (
        .clk     (clk),                 // input
        .rst_n   (rst_n),               // input
        .psel    (psel),                // input
        .penable (penable),             // input
        .pwrite  (pwrite),              // input
        .paddr   (paddr[7:0]),          // input
        .pwdata  (pwdata[31:0]),        // input
        .prdata  (timer_prdata[31:0]),  // output
        .pready  (timer_pready),        // output
        .tick    (timer_tick),          // output
        .timeout (timer_timeout)        // output
    );

endmodule