// ============================================================================
// vibe_soc_top
// ============================================================================
// AUTO-GENERATED by soc_integrate.py
// Timestamp: 2026-06-21T21:57:13.078350
//
// DO NOT EDIT THIS FILE DIRECTLY.
// Modify sub-modules and re-run: soc_integrate.py integrate ...
// For manual connections, use assign statements in a separate file.
// ============================================================================

module vibe_soc_top (
    input         clk,
    input         rst_n,
    input  [7:0]  data_in,
    input         valid_in,
    output [7:0]  bus_data_out,
    output        bus_valid_out,
    input  [7:0]  uart_tx_data,
    input         uart_tx_valid,
    output        uart_tx_ready,
    output        uart_tx_busy,
    output        uart_tx_done,
    output        uart_tx,
    input         uart_rx,
    output [7:0]  uart_rx_data,
    output        uart_rx_valid,
    output        uart_rx_busy,
    output        uart_rx_frame_err,
    input  [15:0] uart_baud_div
);

    // Internal shared signals
    wire [7:0] core_data_out;
    wire core_valid_out;

    core u_core (
        .clk       (clk),                 // input
        .rst_n     (rst_n),               // input
        .data_in   (data_in[7:0]),        // input
        .valid_in  (valid_in),            // input
        .data_out  (core_data_out[7:0]),  // output
        .valid_out (core_valid_out)       // output
    );

    bus u_bus (
        .clk       (clk),                 // input
        .rst_n     (rst_n),               // input
        .data_in   (core_data_out[7:0]),  // input
        .valid_in  (core_valid_out),      // input
        .data_out  (bus_data_out[7:0]),   // output
        .valid_out (bus_valid_out)        // output
    );

    uart u_uart (
        .clk          (clk),                 // input
        .rst_n        (rst_n),               // input
        .tx_data      (uart_tx_data[7:0]),   // input
        .tx_valid     (uart_tx_valid),       // input
        .tx_ready     (uart_tx_ready),       // output
        .tx_busy      (uart_tx_busy),        // output
        .tx_done      (uart_tx_done),        // output
        .tx_out       (uart_tx),             // output
        .rx_in        (uart_rx),             // input
        .rx_data      (uart_rx_data[7:0]),   // output
        .rx_valid     (uart_rx_valid),       // output
        .rx_busy      (uart_rx_busy),        // output
        .rx_frame_err (uart_rx_frame_err),   // output
        .baud_div     (uart_baud_div[15:0])  // input
    );

endmodule