// chip/top ordered RTL fragment.
// Assembled by chip/top/de/rtl/filelist.mk.

// Canonical OpenTitan Earlgrey DUT RTL/model filelist for vibe_soc chip/top.
// Source order is frozen from the known-good FuseSoC top_earlgrey_chip_sim dependency graph.
// DV/UVM/DPI/SVA/bind sources live in chip/top/dv/tb/filelist.f.

+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/model
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils

$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/jtag_id_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/top_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_ack_sm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_main_sm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/jtag_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otp_macro/rtl/otp_macro_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/model/crypto.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/model/aes.c
-f $SOC/ip/digital/opentitan_common/de/rtl/filelist.f
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/top_earlgrey_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/scan_role_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_icache.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_tracer_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/vendor/lowrisc_ibex/rtl/ibex_tracer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_core_ibex/rtl/rv_core_ibex_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_blanker.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_subst_perm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_present.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_prince.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_count_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_count.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_mux2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pad_attr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_pad_wrapper.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_1r1w.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_ram_2p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_rom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_gf_mult.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_lfsr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_max_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_msb_extend.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_dom_and_2share.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_const.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_pad.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sha2_32.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_sum_tree.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/physical_pads.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/ibex_pmp_reset_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_double_lfsr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_clock_inv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flop_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_leading_one_ppc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi4_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi8_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi12_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi16_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi20_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi24_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi28_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_sender.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_mubi32_dec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_enc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_mux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_onehot_check.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1p_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_1r1w_async_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_rom_adv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_trivium_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/rtl/prim_trivium.sv
