// chip/top ordered RTL fragment.
// Assembled by chip/top/de/rtl/filelist.mk.

$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim_generic/rtl/prim_flash.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/gpio/rtl/gpio.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_chan.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwm/rtl/pwm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_por.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_crash_info.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_leaf_rst.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex_cfg_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex_addr_trans.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_core_ibex/rtl/rv_core_ibex.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_intr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/adc_ctrl/rtl/adc_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctrl_reg_shadowed.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctrl_gcm_reg_shadowed.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr_fsm_p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ctr_fsm_n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control_fsm_p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_control_fsm_n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_reg_status.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sel_buf_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sub_bytes.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_lut.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_sbox_dom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_shift_rows.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_mix_columns.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_mix_single_column.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_key_expand.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_prng_clearing.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_prng_masking.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes_ghash.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/rtl/aes.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aon_timer/rtl/aon_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_ack_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_main_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/edn/rtl/edn.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/hmac/rtl/hmac.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_fifo_sync_sram_adapter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_fifos.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_bus_monitor.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_controller_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c_target_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/i2c/rtl/i2c.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_controller.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_decoder.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_predecode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_instruction_fetch.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_base.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_bignum.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_base_ff.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_bignum_ff.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_base_fpga.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rf_bignum_fpga.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_lsu.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_alu_base.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_alu_bignum.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mac_bignum_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mac_bignum.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mai.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mask_accelerator.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_mod_result_selector.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_loop_controller.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_stack.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_rnd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_sec_add.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_start_stop_control.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_adder.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_multiplier.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_shifter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_vec_transposer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn_scramble_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/otbn/rtl/otbn.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen_chan.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/pattgen/rtl/pattgen.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_dbg_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_dmi_gate.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_dm/rtl/rv_dm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/timer_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rv_timer/rtl/rv_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/sha3_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/keccak_round.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/keccak_2share.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/sha3pad.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/sha3.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_cmdparse.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_dpram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_readsram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_readbuffer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_readcmd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_passthrough.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_status.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_jedec.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_addr_4b.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_fifo2sram_adapter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_csb_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spid_upload.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_tpm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_s2p.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_p2s.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_device/rtl/spi_device.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_cmd_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_shift_register.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_byte_select.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_byte_merge.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_command_queue.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_data_fifos.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host_window.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/rtl/spi_host.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/rtl/sram_ctrl_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/rtl/sram_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_autoblock.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_comboact.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_pin.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_keyintr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_detect.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_combo.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_ulp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl_intr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sysrst_ctrl/rtl/sysrst_ctrl.sv
