// chip/top ordered RTL fragment.
// Assembled by chip/top/de/rtl/filelist.mk.

$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_usbif.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_linkstate.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_iomux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_counter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev_aon_wake.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/usbdev/rtl/usbdev.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/adc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/adc_ana.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vcaon_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_alert.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/aon_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/aon_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/io_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/io_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/sys_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/sys_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/usb_clk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/usb_osc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/gfr_clk_mux2.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_pulse_sync.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/rng.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/ast/rtl/ast_dft.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_main/rtl/autogen/tl_main_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_main/rtl/autogen/xbar_main.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_peri/rtl/autogen/tl_peri_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_peri/rtl/autogen/xbar_peri.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_wrap.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_lpg_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_class.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_esc_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_accu.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_byp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_clk_status.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_meas_chk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_root_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_trans.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_erase.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prog.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_rd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_arb.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_info_cfg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_region_cfg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp_data_region_sel.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buffers.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_prog.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_erase.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_scramble.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_wkup.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_jtag_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_jtag_breakout.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_strap_sampling.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_cdc.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_slow_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_wake_info.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_main_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_state_db.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_cmd_stage.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_block_encrypt.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_ctr_drbg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/csrng/rtl/csrng.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_watermark_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_field_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_cntr_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_main_sm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_repcnts_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_enable_delay.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/entropy_src/rtl/entropy_src.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/testing/top_earlgrey_rnd_cnst_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_cfg_en.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_data_en_state.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_err.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_input_checks.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_kmac_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_op_state_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_sideload_key.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_core.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_msgfifo.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_staterd.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_app.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_entropy.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac_errchk.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/rtl/kmac.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_dmi_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/rtl/lc_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_regs_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_counter.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_mux.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/rtl/rom_ctrl_scrambled_rom.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_ecc_reg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_scrmbl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_buf.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_kdi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lci.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
