// Canonical OpenTitan Earlgrey DV/UVM/DPI/SVA filelist for vibe_soc chip/top.
// Complements chip/top/de/rtl/filelist.f for dv simulation only.
// Source order is frozen from the known-good FuseSoC top_earlgrey_chip_sim dependency graph.

+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_prince/crypto_dpi_prince
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/detail
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm/mixin
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm/detail/constants
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm/detail
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/vendor/kerukuro_digestpp/algorithm
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/gpiodpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/uartdpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_model
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_reg
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/csr_utils
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pattgen_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pwm_monitor
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/scoreboard
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_dmi_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_riscv_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_riscv_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/env/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/dv/aes_model_dpi
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/tests
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_bkdr_util
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/seq_lib
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/autogen
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tests
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tb
+incdir+$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/autogen
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_present/crypto_dpi_present/crypto_dpi_present.cc
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_present/crypto_dpi_present/crypto_dpi_present_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/digestpp_dpi.cc
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/kmac/dv/dpi/digestpp_dpi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/gpiodpi/gpiodpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/uartdpi/uartdpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi_stream.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi_test.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_crc.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_monitor.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_transfer.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usb_utils.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/gpiodpi/gpiodpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/uartdpi/uartdpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/dpi/usbdpi/usbdpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/pins_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/rst_shadowed_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/dv/env/spi_host_env_cfg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_main/dv/autogen/xbar_main_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip/xbar_peri/dv/autogen/xbar_peri_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/usb20_agent/usb20_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/usb20_agent/usb20_usbdpi.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/tb/xbar_macros.svh
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/common_ifs_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/clk_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/common_ifs/clk_rst_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_prince/crypto_dpi_prince/crypto_dpi_prince.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/prim/dv/prim_prince/crypto_dpi_prince/crypto_dpi_prince_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mgr_lib/pwrmgr_rstmgr_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/str_utils/str_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sw_test_status/sw_test_status_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sw_test_status/sw_test_status_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/bus_params_pkg/bus_params_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils/dv_test_status_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_model/mem_model_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sw_logger_if/sw_logger_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mgr_lib/clkmgr_pwrmgr_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_utils/dv_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_agent/dv_base_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_base_reg/dv_base_reg_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_aon_cg_en_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_cg_en_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_div_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_extclk_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_gated_clock_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_lost_calib_ctrl_en_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_lost_calib_regwen_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_trans_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_clock_enables_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_rstreqs_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_pwrmgr_csr_assert_0/pwrmgr_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/csr_utils/csr_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_onehot_check_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_count_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_sparse_fsm_flop_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_double_lfsr_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/prim_singleton_fifo_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_onehot_check_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_count_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_sparse_fsm_flop_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_double_lfsr_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sec_cm/sec_cm_prim_singleton_fifo_bind.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_dv_chip_ral_pkg_0/chip_ral_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/clkmgr/dv/sva/clkmgr_sec_cm_checker_assert.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_clkmgr_csr_assert_0/clkmgr_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/dv_lib/dv_lib_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sim_sram/tlul_sink.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sim_sram/sim_sram_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/sim_sram/sim_sram.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/alert_esc_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/alert_esc_probe_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/alert_esc_agent/alert_esc_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent/jtag_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent/jtag_mon_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_agent/jtag_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pattgen_agent/pattgen_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pattgen_agent/pattgen_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent/push_pull_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/push_pull_agent/push_pull_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pwm_monitor/pwm_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/pwm_monitor/pwm_monitor_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/scoreboard/scoreboard_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent/spi_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/spi_agent/spi_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent/tl_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/tl_agent/tl_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent/uart_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/uart_agent/uart_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_base_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_mubi_cov_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_mubi_cov_wrapper.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/cip_lib/cip_lc_tx_cov_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_dmi_agent/jtag_dmi_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_dmi_agent/jtag_rv_debugger_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/jtag_riscv_agent/jtag_riscv_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/lc_ctrl/dv/env/lc_ctrl_dv_utils_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/env/xbar_env_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/dv/aes_model_dpi/aes_model_dpi.c
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/aes/dv/aes_model_dpi/aes_model_dpi_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/i2c_agent/i2c_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/dv/sva/spi_host_data_stable_sva.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/spi_host/dv/sva/spi_host_bind.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_spi_host_csr_assert_0/spi_host_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/tlul/generic_dv/tests/xbar_test_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_attrs_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_cascading_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_rst_en_track_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_sw_rst_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/dv/sv/mem_bkdr_util/mem_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/rstmgr/dv/sva/rstmgr_bind.sv
$SOC/chip/top/de/rtl/generated/opentitan_fusesoc/src/lowrisc_fpv_rstmgr_csr_assert_0/rstmgr_csr_assert_fpv.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/dv/env/sram_scrambler_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/sram_ctrl/dv/env/sram_ctrl_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_ctrl_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_scrambler_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/ip_autogen/otp_ctrl/dv/env/otp_ctrl_mem_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/ip/rom_ctrl/dv/env/rom_ctrl_bkdr_util_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/chip_common_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/chip_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/chip_env_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/alerts_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/ast_ext_clk_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/ast_supply_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/pwrmgr_low_power_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/rstmgr_cnsty_fault_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/flash_ctrl_host_gnt_fault_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/tb_dpi_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/env/top_earlgrey_error_injection_ifs_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/sva/clk_ctrl_and_main_pd_sva_if.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/sva/top_earlgrey_bind.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tests/chip_test_pkg.sv
$SOC/chip/top/de/rtl/vendor/opentitan/hw/top_earlgrey/dv/tb/tb.sv
