# opentitan_common - RTL Filelist Dependencies

ifndef OPENTITAN_COMMON_FILELIST_MK
OPENTITAN_COMMON_FILELIST_MK := 1

OPENTITAN_COMMON_RTL_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
OPENTITAN_COMMON_FILELIST := $(OPENTITAN_COMMON_RTL_DIR)filelist.f
OPENTITAN_COMMON_FRAGMENT_10_TOP00_PRIM_BLOCK1 := $(OPENTITAN_COMMON_RTL_DIR)fragments/10_top00_prim_block1.f
OPENTITAN_COMMON_FRAGMENT_20_TOP00_PRIM_BLOCK2 := $(OPENTITAN_COMMON_RTL_DIR)fragments/20_top00_prim_block2.f
OPENTITAN_COMMON_FRAGMENT_30_TOP10_PRIM_BLOCK1 := $(OPENTITAN_COMMON_RTL_DIR)fragments/30_top10_prim_block1.f

ifneq ($(OPENTITAN_COMMON_NO_AUTO_REGISTER),1)
ifeq (,$(filter $(OPENTITAN_COMMON_FILELIST),$(MODULE_FILELISTS)))
  MODULE_FILELISTS += $(OPENTITAN_COMMON_FILELIST)
endif
ifeq (,$(filter $(OPENTITAN_COMMON_FRAGMENT_10_TOP00_PRIM_BLOCK1),$(MODULE_FILELISTS)))
  MODULE_FILELISTS += $(OPENTITAN_COMMON_FRAGMENT_10_TOP00_PRIM_BLOCK1)
endif
ifeq (,$(filter $(OPENTITAN_COMMON_FRAGMENT_20_TOP00_PRIM_BLOCK2),$(MODULE_FILELISTS)))
  MODULE_FILELISTS += $(OPENTITAN_COMMON_FRAGMENT_20_TOP00_PRIM_BLOCK2)
endif
ifeq (,$(filter $(OPENTITAN_COMMON_FRAGMENT_30_TOP10_PRIM_BLOCK1),$(MODULE_FILELISTS)))
  MODULE_FILELISTS += $(OPENTITAN_COMMON_FRAGMENT_30_TOP10_PRIM_BLOCK1)
endif
endif

endif
