#!/usr/bin/env python3
"""Generated by scripts/sync_loop_state_entrypoints.py; do not edit."""

from loop_state_core import migrate_main, migrate_state, migrate_state_data

main = migrate_main

if __name__ == "__main__":
    raise SystemExit(main())
