#!/usr/bin/env python3
"""Generated by scripts/sync_loop_state_entrypoints.py; do not edit."""

from loop_state_core import query_main, query_state

main = query_main

if __name__ == "__main__":
    raise SystemExit(main())
