#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
unset PYTHONHOME PYTHONPATH PYTHONVERSION

plugin_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
requirements=$plugin_root/mcp-requirements.txt
venv_dir=${SILICON_CREW_MCP_VENV:-${SOC_MCP_VENV:-${XDG_CACHE_HOME:-$HOME/.cache}/silicon-crew/venv}}
required_modules="mcp openpyxl pandas yaml xlrd"

python_is_compatible() {
    candidate=$1
    [ -x "$candidate" ] || return 1
    "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' >/dev/null 2>&1
}

python_has_modules() {
    candidate=$1
    python_is_compatible "$candidate" || return 1
    "$candidate" -c '
import importlib.util, sys
required = sys.argv[1:]
raise SystemExit(0 if all(importlib.util.find_spec(name) is not None for name in required) else 1)
' $required_modules >/dev/null 2>&1
}

requirements_stamp() {
    cksum "$requirements" | awk '{print $1 ":" $2}'
}

runtime_is_current() {
    candidate=$venv_dir/bin/python
    stamp_file=$venv_dir/.silicon-crew-requirements
    python_has_modules "$candidate" || return 1
    [ -f "$stamp_file" ] || return 1
    [ "$(sed -n '1p' "$stamp_file")" = "$(requirements_stamp)" ]
}

find_bootstrap_python() {
    if [ -n "${SILICON_CREW_BOOTSTRAP_PYTHON:-}" ]; then
        candidate=$SILICON_CREW_BOOTSTRAP_PYTHON
        if [ ! -x "$candidate" ]; then
            candidate=$(command -v "$candidate" 2>/dev/null || true)
        fi
        if [ -n "$candidate" ] && python_is_compatible "$candidate"; then
            printf '%s
' "$candidate"
            return 0
        fi
        return 1
    fi
    for name in python3.13 python3.12 python3.11 python3.10 python3; do
        candidate=$(command -v "$name" 2>/dev/null || true)
        if [ -n "$candidate" ] && python_is_compatible "$candidate"; then
            printf '%s
' "$candidate"
            return 0
        fi
    done
    return 1
}

acquire_install_lock() {
    lock_file=$venv_dir.install.lock
    mkdir -p "$(dirname -- "$venv_dir")"
    command -v flock >/dev/null 2>&1 || {
        echo "silicon-crew MCP: flock is required for runtime setup" >&2
        exit 127
    }
    exec 9>"$lock_file"
    flock -w 120 9 || {
        echo "silicon-crew MCP: timed out waiting for runtime lock: $lock_file" >&2
        exit 127
    }
}

release_install_lock() {
    flock -u 9 || true
}

install_runtime() {
    [ -f "$requirements" ] || {
        echo "silicon-crew MCP: requirements not found: $requirements" >&2
        exit 127
    }
    acquire_install_lock
    if runtime_is_current; then
        release_install_lock
        return 0
    fi
    if [ ! -x "$venv_dir/bin/python" ]; then
        base=$(find_bootstrap_python) || {
            echo "silicon-crew MCP: no Python >=3.10 found" >&2
            exit 127
        }
        echo "silicon-crew MCP: creating runtime at $venv_dir" >&2
        "$base" -m venv "$venv_dir" >&2
    fi
    echo "silicon-crew MCP: installing dependencies from $requirements" >&2
    "$venv_dir/bin/python" -m pip install --disable-pip-version-check -r "$requirements" >&2
    python_has_modules "$venv_dir/bin/python" || {
        echo "silicon-crew MCP: dependency validation failed after install" >&2
        exit 127
    }
    requirements_stamp >"$venv_dir/.silicon-crew-requirements"
    release_install_lock
}

configured_python=${SILICON_CREW_PYTHON:-${SOC_MCP_PYTHON:-}}
if [ -n "$configured_python" ]; then
    if ! python_has_modules "$configured_python"; then
        echo "silicon-crew MCP: configured Python lacks Python>=3.10 or required modules" >&2
        echo "Unset SILICON_CREW_PYTHON/SOC_MCP_PYTHON or run .agents/scripts/setup_mcp_env.sh" >&2
        exit 127
    fi
    python=$configured_python
else
    if ! runtime_is_current; then
        install_runtime
    fi
    python=$venv_dir/bin/python
fi

if [ "${1:-}" = "--setup-only" ]; then
    printf 'silicon-crew MCP environment ready: %s
' "$python"
    exit 0
fi

[ "$#" -gt 0 ] || {
    echo "Usage: scripts/mcp_python.sh <server_script.py> [args...]" >&2
    exit 2
}
exec "$python" "$@"
