#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
unset NODE_OPTIONS NODE_PATH NPM_CONFIG_PREFIX

plugin_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
repo_root=$(CDPATH= cd -- "$plugin_root/.." && pwd -P)
skill_dir=$plugin_root/skills/wavedrom-gen
package_json=$skill_dir/package.json
package_lock=$skill_dir/package-lock.json
runtime_root=${SILICON_CREW_NODE_HOME:-${SOC_MCP_NODE_HOME:-$repo_root/tmp/wavedrom-runtime}}
pinned_node_version=v22.23.2
install_schema=2
node=
npm_cli=
setup_only=0
if [ "${1:-}" = "--setup-only" ]; then
    setup_only=1
    shift
fi

node_is_compatible() {
    candidate=$1
    [ -x "$candidate" ] || return 1
    "$candidate" -e 'const major = Number(process.versions.node.split(".")[0]); process.exit(major >= 20 ? 0 : 1)' >/dev/null 2>&1
}

node_is_pinned() {
    candidate=$1
    [ -x "$candidate" ] || return 1
    [ "$("$candidate" --version 2>/dev/null)" = "$pinned_node_version" ]
}


select_portable_metadata() {
    system_name=$(uname -s)
    if [ "$system_name" != Linux ]; then
        echo "silicon-crew MCP: portable Node setup supports Linux only (found $system_name)" >&2
        exit 127
    fi
    if command -v ldd >/dev/null 2>&1; then
        ldd_output=$(ldd --version 2>&1 || true)
        case "$ldd_output" in
            *musl*|*Musl*)
                echo "silicon-crew MCP: portable Node setup requires glibc; musl is unsupported" >&2
                exit 127
                ;;
        esac
    fi

    machine=$(uname -m)
    case "$machine" in
        x86_64|amd64)
            node_platform=linux-x64
            expected_sha256=d60acfe00a2932254bb0ad20e01b0d74397a0875595de719654b214f4b03f307
            ;;
        aarch64|arm64)
            node_platform=linux-arm64
            expected_sha256=fff4078c5def658577f92c88db7db3bc0072924bfb93fe52c1e744a54e94abb8
            ;;
        *)
            echo "silicon-crew MCP: unsupported Node runtime architecture: $machine" >&2
            exit 127
            ;;
    esac
    node_bundle=node-$pinned_node_version-$node_platform
    archive=$node_bundle.tar.xz
    node_dir=$runtime_root/$node_bundle
    node_url=https://nodejs.org/dist/$pinned_node_version/$archive
}

acquire_install_lock() {
    lock_file=$runtime_root/install.lock
    mkdir -p "$runtime_root"
    command -v flock >/dev/null 2>&1 || {
        echo "silicon-crew MCP: flock is required for Node runtime setup" >&2
        exit 127
    }
    exec 8>"$lock_file"
    flock -w 180 8 || {
        echo "silicon-crew MCP: timed out waiting for Node runtime lock: $lock_file" >&2
        exit 127
    }
}

release_install_lock() {
    flock -u 8 || true
    exec 8>&-
}

archive_is_valid() {
    candidate=$1
    [ -f "$candidate" ] || return 1
    actual_sha256=$(sha256sum "$candidate" | awk '{print $1}')
    [ "$actual_sha256" = "$expected_sha256" ]
}

ensure_portable_node() {
    select_portable_metadata
    portable_node=$node_dir/bin/node
    if node_is_pinned "$portable_node"; then
        node=$portable_node
        return 0
    fi

    acquire_install_lock
    if node_is_pinned "$portable_node"; then
        node=$portable_node
        release_install_lock
        return 0
    fi
    [ ! -e "$node_dir" ] || {
        echo "silicon-crew MCP: invalid cached Node runtime: $node_dir" >&2
        exit 127
    }
    for required_command in curl sha256sum tar mktemp; do
        command -v "$required_command" >/dev/null 2>&1 || {
            echo "silicon-crew MCP: $required_command is required for Node runtime setup" >&2
            exit 127
        }
    done

    archive_path=$runtime_root/$archive
    if ! archive_is_valid "$archive_path"; then
        download_path=$(mktemp "$runtime_root/node-download.XXXXXX")
        echo "silicon-crew MCP: downloading Node $pinned_node_version for $node_platform" >&2
        if ! curl -fL --connect-timeout 15 --max-time 600 --retry 3 --retry-delay 2 "$node_url" -o "$download_path"; then
            rm -f "$download_path"
            echo "silicon-crew MCP: Node runtime download failed" >&2
            exit 127
        fi
        if ! archive_is_valid "$download_path"; then
            rm -f "$download_path"
            echo "silicon-crew MCP: Node archive checksum validation failed" >&2
            exit 127
        fi
        mv "$download_path" "$archive_path"
    fi

    extract_dir=$(mktemp -d "$runtime_root/extract.XXXXXX")
    tar -xJf "$archive_path" -C "$extract_dir"
    node_is_pinned "$extract_dir/$node_bundle/bin/node" || {
        echo "silicon-crew MCP: extracted Node runtime is invalid" >&2
        exit 127
    }
    mv "$extract_dir/$node_bundle" "$node_dir"
    rmdir "$extract_dir"
    node=$portable_node
    release_install_lock
}

acquire_dependency_lock() {
    lock_dir=$repo_root/tmp/wavedrom-runtime-locks
    mkdir -p "$lock_dir"
    command -v flock >/dev/null 2>&1 || {
        echo "silicon-crew MCP: flock is required for WaveDrom dependency setup" >&2
        exit 127
    }
    dependency_lock=$lock_dir/dependencies.lock
    exec 9>"$dependency_lock"
    flock -w 180 9 || {
        echo "silicon-crew MCP: timed out waiting for WaveDrom dependency lock" >&2
        exit 127
    }
}

release_dependency_lock() {
    flock -u 9 || true
    exec 9>&-
}

dependency_stamp() {
    package_sha256=$(sha256sum "$package_json" | awk '{print $1}')
    package_lock_sha256=$(sha256sum "$package_lock" | awk '{print $1}')
    node_version=$("$node" --version)
    npm_version=$("$node" "$npm_cli" --version)
    platform=$(uname -s)-$(uname -m)
    printf 'install_schema=%s\npackage_sha256=%s\npackage_lock_sha256=%s\nnode_version=%s\nnpm_version=%s\nplatform=%s\n' "$install_schema" "$package_sha256" "$package_lock_sha256" "$node_version" "$npm_version" "$platform"
}

dependencies_are_current() {
    stamp_file=$skill_dir/node_modules/.silicon-crew-wavedrom-lock
    [ -f "$package_json" ] && [ -f "$package_lock" ] || return 1
    [ -f "$stamp_file" ] || return 1
    [ "$(cat "$stamp_file")" = "$(dependency_stamp)" ] || return 1
    (
        cd "$skill_dir"
        "$node" --input-type=module -e "await Promise.all([import('wavedrom'), import('json5'), import('@resvg/resvg-js')])"
    ) >/dev/null 2>&1
}

configure_npm() {
    node_prefix=$(CDPATH= cd -- "$(dirname -- "$node")/.." && pwd -P)
    candidate=$node_prefix/lib/node_modules/npm/bin/npm-cli.js
    if [ -f "$candidate" ]; then
        npm_cli=$candidate
        return 0
    fi
    return 1
}

install_dependencies() {
    [ -f "$skill_dir/package.json" ] && [ -f "$package_lock" ] || {
        echo "silicon-crew MCP: wavedrom-gen package files are missing" >&2
        exit 127
    }
    mkdir -p "$runtime_root/npm-cache"
    echo "silicon-crew MCP: installing wavedrom-gen dependencies from package-lock.json" >&2
    (
        cd "$skill_dir"
        "$node" "$npm_cli" ci --omit=dev --ignore-scripts --no-audit --no-fund --cache "$runtime_root/npm-cache"
    ) >&2
    dependency_stamp >"$skill_dir/node_modules/.silicon-crew-wavedrom-lock"
    dependencies_are_current || {
        echo "silicon-crew MCP: wavedrom-gen dependency validation failed after install" >&2
        exit 127
    }
}

configured_node=${SILICON_CREW_NODE:-${SOC_MCP_NODE:-}}
if [ -n "$configured_node" ]; then
    if [ ! -x "$configured_node" ]; then
        configured_node=$(command -v "$configured_node" 2>/dev/null || true)
    fi
    node_is_compatible "$configured_node" || {
        echo "silicon-crew MCP: configured Node must be executable and version >=20" >&2
        exit 127
    }
    node=$configured_node
else
    select_portable_metadata
    portable_node=$node_dir/bin/node
    if node_is_pinned "$portable_node"; then
        node=$portable_node
    elif [ "$setup_only" -eq 1 ]; then
        ensure_portable_node
    else
        echo "silicon-crew MCP: WaveDrom Node runtime is not prepared" >&2
        echo "Run: make mcp-setup" >&2
        exit 127
    fi
fi

configure_npm || {
    echo "silicon-crew MCP: selected Node has no bundled npm CLI; unset the Node override and run: make mcp-setup" >&2
    exit 127
}

if ! dependencies_are_current; then
    if [ "$setup_only" -ne 1 ]; then
        echo "silicon-crew MCP: WaveDrom dependencies are not prepared" >&2
        echo "Run: make mcp-setup" >&2
        exit 127
    fi
    acquire_dependency_lock
    if ! dependencies_are_current; then
        install_dependencies
    fi
    release_dependency_lock
fi

if [ "$setup_only" -eq 1 ]; then
    printf 'silicon-crew WaveDrom environment ready: %s\n' "$node"
    exit 0
fi

[ "$#" -gt 0 ] || {
    echo "Usage: scripts/mcp_node.sh <server_script.mjs> [args...]" >&2
    exit 2
}
exec "$node" "$@"
