#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
plugin_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
exec /bin/sh "$plugin_root/scripts/run_mcp_python.sh" --setup-only
