#!/usr/bin/env python3
"""Generated by scripts/sync_loop_state_entrypoints.py; do not edit."""

from loop_state_core import update_main, update_state

main = update_main

if __name__ == "__main__":
    raise SystemExit(main())
