// soc_ip_common - synthesizable library used by CRG / platform IP
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_and.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_or.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_nand.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_inv.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_buf.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_clk_or.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_clk_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_icg.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_sync.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/icg.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/sync.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_cnt.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/ss_rst_sequence.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/xstar_por_sequence.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_divider.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_glitch_free_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clkselNway_f0_2.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_buf_for_occ.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_glitch_free_switch.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_divider_wrap.v
$SOC/ip/digital/soc_ip_common/de/rtl/cdc/pulse_sync_h2s.v
// Pad / IO behavioral models (io-top-gen, DV smoke; not foundry cells)
$SOC/ip/digital/soc_ip_common/de/rtl/pad/test_tdr_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/pad/std_cell_clk_buf.v
$SOC/ip/digital/soc_ip_common/de/rtl/pad/iobuf_model.v
$SOC/ip/digital/soc_ip_common/de/rtl/pad/iobuf_s_model.v
$SOC/ip/digital/soc_ip_common/de/rtl/pad/clkbuf_model.v
