$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_divider.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_and.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v
$SOC/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_cnt.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_icg.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_or.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_inv.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_buf.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_nand.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_sync.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_clk_mux.v
$SOC/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_clk_or.v
$SOC/ip/digital/soc_ip_common/de/rtl/clk_gen/clk_glitch_free_mux.v
