# Generated by silicon-crew soc-openroad. Keep this file in the design repo.
THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
PROJECT_ROOT := $(abspath $(THIS_DIR)/../../../..)
export DESIGN_NAME = vibe_soc_top
export DESIGN_NICKNAME = vibe_soc_top
export PLATFORM = nangate45

export VERILOG_FILES = \
  $(PROJECT_ROOT)/chip/top/de/rtl/vibe_soc_top.v \
  $(PROJECT_ROOT)/chip/core/de/rtl/core.v \
  $(PROJECT_ROOT)/chip/bus/de/rtl/bus.v \
  $(PROJECT_ROOT)/ip/digital/uart/de/rtl/uart.v

export SDC_FILE = $(THIS_DIR)/constraint.sdc
export ABC_AREA ?= 1
export CORE_UTILIZATION ?= 55
export TNS_END_PERCENT ?= 100
export SYNTH_REPEATABLE_BUILD ?= 1
export PLACE_DENSITY_LB_ADDON ?= 0.20
export PDN_TCL ?= $(PLATFORM_DIR)/grid_strategy-M1-M4-M7.tcl
