#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
exec /bin/sh "$repo_root/.agents/scripts/run_mcp_node.sh" "$@"
