#!/usr/bin/env python3
"""Generate or check the repository's Codex and generic MCP configs."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / ".agents/mcp-servers.json"
CODEX_CONFIG = ROOT / ".codex/config.toml"
GENERIC_CONFIG = ROOT / ".mcp.json"


def load_manifest() -> dict[str, Any]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise ValueError("unsupported MCP manifest schema_version")
    launcher = manifest.get("launcher")
    servers = manifest.get("servers")
    if not isinstance(launcher, str) or Path(launcher).is_absolute():
        raise ValueError("manifest launcher must be a repository-relative path")
    if not isinstance(servers, list) or not servers:
        raise ValueError("manifest servers must be a non-empty list")

    names: set[str] = set()
    for server in servers:
        if not isinstance(server, dict):
            raise ValueError("every manifest server must be an object")
        name = server.get("name")
        script = server.get("script")
        if not isinstance(name, str) or not name or name in names:
            raise ValueError(f"invalid or duplicate MCP server name: {name!r}")
        if not isinstance(script, str) or Path(script).is_absolute():
            raise ValueError(f"server {name}: script must be repository-relative")
        for field in ("startup_timeout_sec", "tool_timeout_sec"):
            value = server.get(field)
            if not isinstance(value, int) or value <= 0:
                raise ValueError(f"server {name}: {field} must be a positive integer")
        if not isinstance(server.get("default_enabled"), bool):
            raise ValueError(f"server {name}: default_enabled must be boolean")
        names.add(name)
    return manifest


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_codex(manifest: dict[str, Any]) -> str:
    launcher = manifest["launcher"]
    lines = [
        "# Generated by scripts/sync_mcp_configs.py from .agents/mcp-servers.json.",
        "# Edit the manifest, then run: python3 scripts/sync_mcp_configs.py --write",
        "",
    ]
    for server in manifest["servers"]:
        lines.extend(
            [
                f"[mcp_servers.{server['name']}]",
                f"enabled = {str(server['default_enabled']).lower()}",
                'command = "/bin/sh"',
                'cwd = "."',
                f"args = [{toml_string(launcher)}, {toml_string(server['script'])}]",
                f"startup_timeout_sec = {server['startup_timeout_sec']}",
                f"tool_timeout_sec = {server['tool_timeout_sec']}",
                "",
            ]
        )

    lines.extend(
        [
            "[[hooks.PreToolUse]]",
            'matcher = "Bash|functions.exec_command|exec_command"',
            "",
            "[[hooks.PreToolUse.hooks]]",
            'type = "command"',
            "command = 'bash \"$(git rev-parse --show-toplevel)/.codex/hooks/pre-tool-use.sh\"'",
            "timeout = 30",
            'statusMessage = "Checking EDA command policy"',
            "",
        ]
    )
    return "\n".join(lines)


def render_generic(manifest: dict[str, Any]) -> str:
    prefix = manifest.get("client_prefix", "")
    launcher = manifest["launcher"]
    servers = {
        f"{prefix}{server['name']}": {
            "type": "stdio",
            "command": "sh",
            "args": [launcher, server["script"]],
        }
        for server in manifest["servers"]
    }
    return json.dumps({"mcpServers": servers}, indent=2, ensure_ascii=False) + "\n"


def expected_configs() -> dict[Path, str]:
    manifest = load_manifest()
    return {
        CODEX_CONFIG: render_codex(manifest),
        GENERIC_CONFIG: render_generic(manifest),
    }


def check() -> int:
    mismatches: list[Path] = []
    for path, expected in expected_configs().items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != expected:
            mismatches.append(path)
    if mismatches:
        for path in mismatches:
            print(f"[MCP-CONFIG] OUT-OF-DATE: {path.relative_to(ROOT)}", file=sys.stderr)
        print("Run: python3 scripts/sync_mcp_configs.py --write", file=sys.stderr)
        return 2
    print("[MCP-CONFIG] Configs match .agents/mcp-servers.json")
    return 0


def write() -> int:
    for path, content in expected_configs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"[MCP-CONFIG] Wrote {path.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify configs (default)")
    mode.add_argument("--write", action="store_true", help="regenerate both configs")
    args = parser.parse_args()
    try:
        return write() if args.write else check()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"[MCP-CONFIG] ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
