#!/usr/bin/env python3
"""Generate or check Grok Build MCP config from .agents/mcp-servers.json.

Grok rejects colon-prefixed server names (e.g. silicon-crew:soc-build) and
ends up with tool_count=0. This adapter uses silicon-crew-<name> with hyphens.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from sync_mcp_configs import load_manifest

ROOT = Path(__file__).resolve().parents[1]
GROK_CONFIG = ROOT / ".grok" / "config.toml"


def render_grok(manifest: dict[str, Any]) -> str:
    from sync_mcp_configs import is_remote_server

    launcher = manifest["launcher"]
    lines = [
        "# Generated by scripts/sync_grok_mcp_config.py from .agents/mcp-servers.json.",
        '# DO NOT put colon-prefixed names here — Grok rejects ":" in server names.',
        "# Codex uses .codex/config.toml; Claude uses .mcp.json (silicon-crew:… keys).",
        "# Remote/official HTTP servers keep bare names (e.g. drawio).",
        "# Priority for Grok: this file > .mcp.json.",
        "",
    ]
    for server in manifest["servers"]:
        # Remote HTTP servers are external (no silicon-crew- prefix).
        name = server["name"] if is_remote_server(server) else f"silicon-crew-{server['name']}"
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f"enabled = {str(server['default_enabled']).lower()}")
        if is_remote_server(server):
            lines.append(f"url = {json.dumps(server['url'])}")
            headers = server.get("headers")
            if headers:
                lines.append(f"headers = {json.dumps(headers, ensure_ascii=False)}")
        elif "script" in server:
            lines.append('command = "/bin/sh"')
            lines.append(
                f'args = ["{launcher}", "{server["script"]}"]'
            )
            lines.append('cwd = "."')
        else:
            lines.append(f"command = {json.dumps(server['command'])}")
            if server.get("cwd") is not None:
                lines.append(f"cwd = {json.dumps(server['cwd'])}")
            lines.append(f"args = {json.dumps(server.get('args', []))}")
        lines.append(f"startup_timeout_sec = {server['startup_timeout_sec']}")
        lines.append(f"tool_timeout_sec = {server['tool_timeout_sec']}")
        lines.append("")
    return "\n".join(lines)


def check() -> int:
    expected = render_grok(load_manifest())
    actual = GROK_CONFIG.read_text(encoding="utf-8") if GROK_CONFIG.is_file() else ""
    if actual != expected:
        print(f"[GROK-MCP] OUT-OF-DATE: {GROK_CONFIG.relative_to(ROOT)}", file=sys.stderr)
        print("Run: python3 scripts/sync_grok_mcp_config.py --write", file=sys.stderr)
        return 2
    print("[GROK-MCP] Config matches .agents/mcp-servers.json")
    return 0


def write() -> int:
    GROK_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    content = render_grok(load_manifest())
    GROK_CONFIG.write_text(content, encoding="utf-8")
    print(f"[GROK-MCP] Wrote {GROK_CONFIG.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    try:
        return write() if args.write else check()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"[GROK-MCP] ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
