#!/usr/bin/env python3
"""Generate thin, compatibility-preserving loop-state entrypoints.

The generated files intentionally contain no state semantics.  All behavior
lives in ``.agents/scripts/loop_state_core.py`` so init, update, query, and
review cannot drift apart again.
"""

from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path


HEADER = """#!/usr/bin/env python3
\"\"\"Generated by scripts/sync_loop_state_entrypoints.py; do not edit.\"\"\"

"""

ENTRYPOINTS = {
    "pipeline_state.py": HEADER
    + "from loop_state_core import (\n"
    + "    DEPENDENCIES, STAGE_META, STAGE_ORDER, SUCCESS_STATES,\n"
    + "    compute_next_actions, dependencies_satisfied, new_pipeline, now,\n"
    + "    parse_check, recompute_blocked,\n"
    + ")\n",
    "init_state.py": HEADER
    + "from loop_state_core import init_state_multi, init_state_single, init_main\n\n"
    + "main = init_main\n\n"
    + "if __name__ == \"__main__\":\n    raise SystemExit(main())\n",
    "update_state.py": HEADER
    + "from loop_state_core import update_main, update_state\n\n"
    + "main = update_main\n\n"
    + "if __name__ == \"__main__\":\n    raise SystemExit(main())\n",
    "query_state.py": HEADER
    + "from loop_state_core import query_main, query_state\n\n"
    + "main = query_main\n\n"
    + "if __name__ == \"__main__\":\n    raise SystemExit(main())\n",
    "check_loop_state.py": HEADER
    + "from loop_state_core import check, check_main\n\n"
    + "main = check_main\n\n"
    + "if __name__ == \"__main__\":\n    raise SystemExit(main())\n",
    "migrate_state.py": HEADER
    + "from loop_state_core import migrate_main, migrate_state, migrate_state_data\n\n"
    + "main = migrate_main\n\n"
    + "if __name__ == \"__main__\":\n    raise SystemExit(main())\n",
}
ENTRYPOINT_MODES = {
    "pipeline_state.py": 0o644,
    "init_state.py": 0o644,
    "update_state.py": 0o644,
    "query_state.py": 0o644,
    "check_loop_state.py": 0o755,
    "migrate_state.py": 0o755,
}


def _atomic_write(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def sync(root: Path, *, check: bool = False) -> list[str]:
    scripts_dir = root.expanduser().resolve() / ".agents" / "scripts"
    if not check:
        scripts_dir.mkdir(parents=True, exist_ok=True)
    changed = []
    for name, content in ENTRYPOINTS.items():
        path = scripts_dir / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        current_mode = path.stat().st_mode & 0o777 if path.exists() else None
        expected_mode = ENTRYPOINT_MODES[name]
        if current == content and current_mode == expected_mode:
            continue
        changed.append(path.relative_to(root.resolve()).as_posix())
        if not check:
            if current == content and path.exists():
                path.chmod(expected_mode)
            else:
                _atomic_write(path, content, expected_mode)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args()
    changed = sync(args.root, check=args.check)
    if changed:
        verb = "would update" if args.check else "updated"
        for path in changed:
            print(f"{verb}: {path}")
        return 1 if args.check else 0
    print("loop-state entrypoints are synchronized")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
