#!/usr/bin/env python3
"""Generate/check MCP launchers and coordinate generated MCP client configs."""

from __future__ import annotations

import argparse
import json
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / ".agents/mcp-servers.json"
REQUIREMENTS = ROOT / ".agents/mcp-requirements.txt"
CONFIG_SYNC = ROOT / "scripts/sync_mcp_configs.py"


def _root_launcher() -> str:
    return """#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
exec /bin/sh "$repo_root/.agents/scripts/run_mcp_python.sh" "$@"
"""


def _node_root_launcher() -> str:
    return """#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
exec /bin/sh "$repo_root/.agents/scripts/run_mcp_node.sh" "$@"
"""


def _runtime_launcher() -> str:
    return """#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
unset PYTHONHOME PYTHONPATH PYTHONVERSION

plugin_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
requirements=$plugin_root/mcp-requirements.txt
venv_dir=${SILICON_CREW_MCP_VENV:-${SOC_MCP_VENV:-${XDG_CACHE_HOME:-$HOME/.cache}/silicon-crew/venv}}
required_modules="mcp openpyxl pandas yaml xlrd"

python_is_compatible() {
    candidate=$1
    [ -x "$candidate" ] || return 1
    "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' >/dev/null 2>&1
}

python_has_modules() {
    candidate=$1
    python_is_compatible "$candidate" || return 1
    "$candidate" -c '
import importlib.util, sys
required = sys.argv[1:]
raise SystemExit(0 if all(importlib.util.find_spec(name) is not None for name in required) else 1)
' $required_modules >/dev/null 2>&1
}

requirements_stamp() {
    cksum "$requirements" | awk '{print $1 ":" $2}'
}

runtime_is_current() {
    candidate=$venv_dir/bin/python
    stamp_file=$venv_dir/.silicon-crew-requirements
    python_has_modules "$candidate" || return 1
    [ -f "$stamp_file" ] || return 1
    [ "$(sed -n '1p' "$stamp_file")" = "$(requirements_stamp)" ]
}

find_bootstrap_python() {
    if [ -n "${SILICON_CREW_BOOTSTRAP_PYTHON:-}" ]; then
        candidate=$SILICON_CREW_BOOTSTRAP_PYTHON
        if [ ! -x "$candidate" ]; then
            candidate=$(command -v "$candidate" 2>/dev/null || true)
        fi
        if [ -n "$candidate" ] && python_is_compatible "$candidate"; then
            printf '%s\n' "$candidate"
            return 0
        fi
        return 1
    fi
    for name in python3.13 python3.12 python3.11 python3.10 python3; do
        candidate=$(command -v "$name" 2>/dev/null || true)
        if [ -n "$candidate" ] && python_is_compatible "$candidate"; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

acquire_install_lock() {
    lock_file=$venv_dir.install.lock
    mkdir -p "$(dirname -- "$venv_dir")"
    command -v flock >/dev/null 2>&1 || {
        echo "silicon-crew MCP: flock is required for runtime setup" >&2
        exit 127
    }
    exec 9>"$lock_file"
    flock -w 120 9 || {
        echo "silicon-crew MCP: timed out waiting for runtime lock: $lock_file" >&2
        exit 127
    }
}

release_install_lock() {
    flock -u 9 || true
}

install_runtime() {
    [ -f "$requirements" ] || {
        echo "silicon-crew MCP: requirements not found: $requirements" >&2
        exit 127
    }
    acquire_install_lock
    if runtime_is_current; then
        release_install_lock
        return 0
    fi
    if [ ! -x "$venv_dir/bin/python" ]; then
        base=$(find_bootstrap_python) || {
            echo "silicon-crew MCP: no Python >=3.10 found" >&2
            exit 127
        }
        echo "silicon-crew MCP: creating runtime at $venv_dir" >&2
        "$base" -m venv "$venv_dir" >&2
    fi
    echo "silicon-crew MCP: installing dependencies from $requirements" >&2
    "$venv_dir/bin/python" -m pip install --disable-pip-version-check -r "$requirements" >&2
    python_has_modules "$venv_dir/bin/python" || {
        echo "silicon-crew MCP: dependency validation failed after install" >&2
        exit 127
    }
    requirements_stamp >"$venv_dir/.silicon-crew-requirements"
    release_install_lock
}

configured_python=${SILICON_CREW_PYTHON:-${SOC_MCP_PYTHON:-}}
if [ -n "$configured_python" ]; then
    if ! python_has_modules "$configured_python"; then
        echo "silicon-crew MCP: configured Python lacks Python>=3.10 or required modules" >&2
        echo "Unset SILICON_CREW_PYTHON/SOC_MCP_PYTHON or run .agents/scripts/setup_mcp_env.sh" >&2
        exit 127
    fi
    python=$configured_python
else
    if ! runtime_is_current; then
        install_runtime
    fi
    python=$venv_dir/bin/python
fi

if [ "${1:-}" = "--setup-only" ]; then
    printf 'silicon-crew MCP environment ready: %s\n' "$python"
    exit 0
fi

[ "$#" -gt 0 ] || {
    echo "Usage: scripts/mcp_python.sh <server_script.py> [args...]" >&2
    exit 2
}
exec "$python" "$@"
"""


def _node_runtime_launcher() -> str:
    return """#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
unset NODE_OPTIONS NODE_PATH NPM_CONFIG_PREFIX

plugin_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
repo_root=$(CDPATH= cd -- "$plugin_root/.." && pwd -P)
skill_dir=$plugin_root/skills/wavedrom-gen
package_json=$skill_dir/package.json
package_lock=$skill_dir/package-lock.json
runtime_root=${SILICON_CREW_NODE_HOME:-${SOC_MCP_NODE_HOME:-$repo_root/tmp/wavedrom-runtime}}
pinned_node_version=v22.23.2
install_schema=2
node=
npm_cli=
setup_only=0
if [ "${1:-}" = "--setup-only" ]; then
    setup_only=1
    shift
fi

node_is_compatible() {
    candidate=$1
    [ -x "$candidate" ] || return 1
    "$candidate" -e 'const major = Number(process.versions.node.split(".")[0]); process.exit(major >= 20 ? 0 : 1)' >/dev/null 2>&1
}

node_is_pinned() {
    candidate=$1
    [ -x "$candidate" ] || return 1
    [ "$("$candidate" --version 2>/dev/null)" = "$pinned_node_version" ]
}


select_portable_metadata() {
    system_name=$(uname -s)
    if [ "$system_name" != Linux ]; then
        echo "silicon-crew MCP: portable Node setup supports Linux only (found $system_name)" >&2
        exit 127
    fi
    if command -v ldd >/dev/null 2>&1; then
        ldd_output=$(ldd --version 2>&1 || true)
        case "$ldd_output" in
            *musl*|*Musl*)
                echo "silicon-crew MCP: portable Node setup requires glibc; musl is unsupported" >&2
                exit 127
                ;;
        esac
    fi

    machine=$(uname -m)
    case "$machine" in
        x86_64|amd64)
            node_platform=linux-x64
            expected_sha256=d60acfe00a2932254bb0ad20e01b0d74397a0875595de719654b214f4b03f307
            ;;
        aarch64|arm64)
            node_platform=linux-arm64
            expected_sha256=fff4078c5def658577f92c88db7db3bc0072924bfb93fe52c1e744a54e94abb8
            ;;
        *)
            echo "silicon-crew MCP: unsupported Node runtime architecture: $machine" >&2
            exit 127
            ;;
    esac
    node_bundle=node-$pinned_node_version-$node_platform
    archive=$node_bundle.tar.xz
    node_dir=$runtime_root/$node_bundle
    node_url=https://nodejs.org/dist/$pinned_node_version/$archive
}

acquire_install_lock() {
    lock_file=$runtime_root/install.lock
    mkdir -p "$runtime_root"
    command -v flock >/dev/null 2>&1 || {
        echo "silicon-crew MCP: flock is required for Node runtime setup" >&2
        exit 127
    }
    exec 8>"$lock_file"
    flock -w 180 8 || {
        echo "silicon-crew MCP: timed out waiting for Node runtime lock: $lock_file" >&2
        exit 127
    }
}

release_install_lock() {
    flock -u 8 || true
    exec 8>&-
}

archive_is_valid() {
    candidate=$1
    [ -f "$candidate" ] || return 1
    actual_sha256=$(sha256sum "$candidate" | awk '{print $1}')
    [ "$actual_sha256" = "$expected_sha256" ]
}

ensure_portable_node() {
    select_portable_metadata
    portable_node=$node_dir/bin/node
    if node_is_pinned "$portable_node"; then
        node=$portable_node
        return 0
    fi

    acquire_install_lock
    if node_is_pinned "$portable_node"; then
        node=$portable_node
        release_install_lock
        return 0
    fi
    [ ! -e "$node_dir" ] || {
        echo "silicon-crew MCP: invalid cached Node runtime: $node_dir" >&2
        exit 127
    }
    for required_command in curl sha256sum tar mktemp; do
        command -v "$required_command" >/dev/null 2>&1 || {
            echo "silicon-crew MCP: $required_command is required for Node runtime setup" >&2
            exit 127
        }
    done

    archive_path=$runtime_root/$archive
    if ! archive_is_valid "$archive_path"; then
        download_path=$(mktemp "$runtime_root/node-download.XXXXXX")
        echo "silicon-crew MCP: downloading Node $pinned_node_version for $node_platform" >&2
        if ! curl -fL --connect-timeout 15 --max-time 600 --retry 3 --retry-delay 2 "$node_url" -o "$download_path"; then
            rm -f "$download_path"
            echo "silicon-crew MCP: Node runtime download failed" >&2
            exit 127
        fi
        if ! archive_is_valid "$download_path"; then
            rm -f "$download_path"
            echo "silicon-crew MCP: Node archive checksum validation failed" >&2
            exit 127
        fi
        mv "$download_path" "$archive_path"
    fi

    extract_dir=$(mktemp -d "$runtime_root/extract.XXXXXX")
    tar -xJf "$archive_path" -C "$extract_dir"
    node_is_pinned "$extract_dir/$node_bundle/bin/node" || {
        echo "silicon-crew MCP: extracted Node runtime is invalid" >&2
        exit 127
    }
    mv "$extract_dir/$node_bundle" "$node_dir"
    rmdir "$extract_dir"
    node=$portable_node
    release_install_lock
}

acquire_dependency_lock() {
    lock_dir=$repo_root/tmp/wavedrom-runtime-locks
    mkdir -p "$lock_dir"
    command -v flock >/dev/null 2>&1 || {
        echo "silicon-crew MCP: flock is required for WaveDrom dependency setup" >&2
        exit 127
    }
    dependency_lock=$lock_dir/dependencies.lock
    exec 9>"$dependency_lock"
    flock -w 180 9 || {
        echo "silicon-crew MCP: timed out waiting for WaveDrom dependency lock" >&2
        exit 127
    }
}

release_dependency_lock() {
    flock -u 9 || true
    exec 9>&-
}

dependency_stamp() {
    package_sha256=$(sha256sum "$package_json" | awk '{print $1}')
    package_lock_sha256=$(sha256sum "$package_lock" | awk '{print $1}')
    node_version=$("$node" --version)
    npm_version=$("$node" "$npm_cli" --version)
    platform=$(uname -s)-$(uname -m)
    printf 'install_schema=%s\\npackage_sha256=%s\\npackage_lock_sha256=%s\\nnode_version=%s\\nnpm_version=%s\\nplatform=%s\\n' "$install_schema" "$package_sha256" "$package_lock_sha256" "$node_version" "$npm_version" "$platform"
}

dependencies_are_current() {
    stamp_file=$skill_dir/node_modules/.silicon-crew-wavedrom-lock
    [ -f "$package_json" ] && [ -f "$package_lock" ] || return 1
    [ -f "$stamp_file" ] || return 1
    [ "$(cat "$stamp_file")" = "$(dependency_stamp)" ] || return 1
    (
        cd "$skill_dir"
        "$node" --input-type=module -e "await Promise.all([import('wavedrom'), import('json5'), import('@resvg/resvg-js')])"
    ) >/dev/null 2>&1
}

configure_npm() {
    node_prefix=$(CDPATH= cd -- "$(dirname -- "$node")/.." && pwd -P)
    candidate=$node_prefix/lib/node_modules/npm/bin/npm-cli.js
    if [ -f "$candidate" ]; then
        npm_cli=$candidate
        return 0
    fi
    return 1
}

install_dependencies() {
    [ -f "$skill_dir/package.json" ] && [ -f "$package_lock" ] || {
        echo "silicon-crew MCP: wavedrom-gen package files are missing" >&2
        exit 127
    }
    mkdir -p "$runtime_root/npm-cache"
    echo "silicon-crew MCP: installing wavedrom-gen dependencies from package-lock.json" >&2
    (
        cd "$skill_dir"
        "$node" "$npm_cli" ci --omit=dev --ignore-scripts --no-audit --no-fund --cache "$runtime_root/npm-cache"
    ) >&2
    dependency_stamp >"$skill_dir/node_modules/.silicon-crew-wavedrom-lock"
    dependencies_are_current || {
        echo "silicon-crew MCP: wavedrom-gen dependency validation failed after install" >&2
        exit 127
    }
}

configured_node=${SILICON_CREW_NODE:-${SOC_MCP_NODE:-}}
if [ -n "$configured_node" ]; then
    if [ ! -x "$configured_node" ]; then
        configured_node=$(command -v "$configured_node" 2>/dev/null || true)
    fi
    node_is_compatible "$configured_node" || {
        echo "silicon-crew MCP: configured Node must be executable and version >=20" >&2
        exit 127
    }
    node=$configured_node
else
    select_portable_metadata
    portable_node=$node_dir/bin/node
    if node_is_pinned "$portable_node"; then
        node=$portable_node
    elif [ "$setup_only" -eq 1 ]; then
        ensure_portable_node
    else
        echo "silicon-crew MCP: WaveDrom Node runtime is not prepared" >&2
        echo "Run: make mcp-setup" >&2
        exit 127
    fi
fi

configure_npm || {
    echo "silicon-crew MCP: selected Node has no bundled npm CLI; unset the Node override and run: make mcp-setup" >&2
    exit 127
}

if ! dependencies_are_current; then
    if [ "$setup_only" -ne 1 ]; then
        echo "silicon-crew MCP: WaveDrom dependencies are not prepared" >&2
        echo "Run: make mcp-setup" >&2
        exit 127
    fi
    acquire_dependency_lock
    if ! dependencies_are_current; then
        install_dependencies
    fi
    release_dependency_lock
fi

if [ "$setup_only" -eq 1 ]; then
    printf 'silicon-crew WaveDrom environment ready: %s\\n' "$node"
    exit 0
fi

[ "$#" -gt 0 ] || {
    echo "Usage: scripts/mcp_node.sh <server_script.mjs> [args...]" >&2
    exit 2
}
exec "$node" "$@"
"""


def _setup_launcher() -> str:
    return """#!/bin/sh
# Generated by scripts/sync_mcp_runtime.py. Do not edit directly.

set -eu
plugin_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
/bin/sh "$plugin_root/scripts/run_mcp_python.sh" --setup-only
exec /bin/sh "$plugin_root/scripts/run_mcp_node.sh" --setup-only
"""


def expected_runtime_files() -> dict[Path, str]:
    return {
        ROOT / "scripts/mcp_python.sh": _root_launcher(),
        ROOT / "scripts/mcp_node.sh": _node_root_launcher(),
        ROOT / ".agents/scripts/run_mcp_python.sh": _runtime_launcher(),
        ROOT / ".agents/scripts/run_mcp_node.sh": _node_runtime_launcher(),
        ROOT / ".agents/scripts/setup_mcp_env.sh": _setup_launcher(),
    }


def validate_inputs() -> None:
    requirements = {
        line.split("#", 1)[0].strip().lower()
        for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines()
        if line.split("#", 1)[0].strip()
    }
    expected_packages = ("mcp", "numpy", "openpyxl", "pandas", "pyyaml", "xlrd")
    for package in expected_packages:
        if not any(item.startswith(package) for item in requirements):
            raise ValueError(f"missing MCP runtime dependency: {package}")

    manifest: dict[str, Any] = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1 or not manifest.get("servers"):
        raise ValueError("invalid or empty MCP server manifest")
    if manifest.get("launcher") != "scripts/mcp_python.sh":
        raise ValueError("MCP manifest must use the generated root launcher")

    wavedrom_dir = ROOT / ".agents/skills/wavedrom-gen"
    for required in ("package.json", "package-lock.json", "scripts/mcp-server.mjs"):
        if not (wavedrom_dir / required).is_file():
            raise ValueError(f"missing wavedrom-gen runtime input: {required}")

    wavedrom = next(
        (server for server in manifest["servers"] if server.get("name") == "wavedrom-gen"),
        None,
    )
    expected_args = [
        "scripts/mcp_node.sh",
        ".agents/skills/wavedrom-gen/scripts/mcp-server.mjs",
        "--stdio",
    ]
    if not wavedrom:
        raise ValueError("missing wavedrom-gen MCP server registration")
    if wavedrom.get("command") != "/bin/sh" or wavedrom.get("args") != expected_args:
        raise ValueError("wavedrom-gen MCP server must use the generated Node launcher")
    if wavedrom.get("cwd") != "." or not wavedrom.get("default_enabled"):
        raise ValueError("wavedrom-gen MCP server must be project-scoped and enabled")


def sync_runtime(write: bool) -> int:
    mismatches: list[Path] = []
    for path, expected in expected_runtime_files().items():
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            print(f"[MCP-RUNTIME] Wrote {path.relative_to(ROOT)}")
        else:
            actual = path.read_text(encoding="utf-8") if path.is_file() else ""
            if actual != expected or not path.stat().st_mode & stat.S_IXUSR:
                mismatches.append(path)
    if mismatches:
        for path in mismatches:
            print(f"[MCP-RUNTIME] OUT-OF-DATE: {path.relative_to(ROOT)}", file=sys.stderr)
        return 2
    return 0


def sync_configs(write: bool) -> int:
    mode = "--write" if write else "--check"
    completed = subprocess.run([sys.executable, str(CONFIG_SYNC), mode], cwd=ROOT, check=False)
    return completed.returncode


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify generated files (default)")
    mode.add_argument("--write", action="store_true", help="regenerate launchers and configs")
    parser.add_argument("--runtime-only", action="store_true", help="skip MCP client config sync")
    args = parser.parse_args()
    try:
        validate_inputs()
        runtime_result = sync_runtime(args.write)
        config_result = 0 if args.runtime_only else sync_configs(args.write)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"[MCP-RUNTIME] ERROR: {exc}", file=sys.stderr)
        return 2
    if runtime_result or config_result:
        if not args.write:
            print("Run: python3 scripts/sync_mcp_runtime.py --write", file=sys.stderr)
        return 2
    print("[MCP-RUNTIME] Runtime and configs are synchronized")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
