// opentitan_prim non-package RTL/model filelist
// Package sources are kept separately in pkg.f.

$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_crc32.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_and2.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_buf.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_clock_buf.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_clock_gating.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_const.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_const_sec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_flop.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_flop_no_rst.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_inv.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_usb_diff_rx.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_xnor2.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_xor2.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_22_16_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_22_16_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_28_22_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_28_22_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_39_32_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_39_32_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_64_57_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_64_57_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_72_64_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_72_64_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_blanker.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_subst_perm.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_present.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_prince.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_count.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_clock_mux2.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_pad_attr.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_pad_wrapper.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_ram_1p.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_ram_1r1w.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_ram_2p.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_rom.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_gf_mult.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_lfsr.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_max_tree.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_msb_extend.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_dom_and_2share.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sec_anchor_const.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sec_anchor_flop.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sha2_pad.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sha2.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sha2_32.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sum_tree.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_double_lfsr.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_clock_inv.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_flop_en.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_leading_one_ppc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi4_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi4_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi4_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi8_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi8_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi8_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi12_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi12_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi12_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi16_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi16_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi16_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi20_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi20_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi20_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi24_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi24_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi24_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi28_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi28_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi28_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi32_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi32_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_mubi32_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_onehot_enc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_onehot_mux.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_onehot_check.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_ram_1p_adv.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_ram_1r1w_async_adv.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_ram_2p_async_adv.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_rom_adv.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_trivium.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_arbiter_fixed.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_arbiter_ppc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_arbiter_tree.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_arbiter_tree_dup.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_diff_decode.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_edge_detector.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_fifo_async_simple.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_fifo_async.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_fifo_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_clock_div.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_rst_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_multibit_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_ram_1p_scr.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_reg_we_check.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_reg_cdc.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_reg_cdc_arb.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_subreg.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_subreg_arb.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_subreg_ext.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_subreg_shadow.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_alert_receiver.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_alert_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_esc_receiver.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_esc_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_lc_dec.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_lc_sender.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_lc_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_racl_error_arb.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_clock_gating_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_hpc2.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_hpc3.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sram_arbiter.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_slicer.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sync_reqack.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sync_reqack_data.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_sync_slow_fast.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_keccak.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_packer.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_packer_fifo.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_gate_gen.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_pulse_sync.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_filter.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_filter_ctr.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_flop_x.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_intr_hw.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_lc_or_hardened.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_edn_req.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_clock_meas.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim/rtl/prim_clock_timeout.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv
$SOC/ip/digital/prim/de/rtl/src/hw/ip/prim_generic/rtl/prim_flash.sv
