# opentitan_tlul - RTL Filelist Dependencies

ifndef OPENTITAN_TLUL_FILELIST_MK
OPENTITAN_TLUL_FILELIST_MK := 1

OPENTITAN_TLUL_RTL_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
OPENTITAN_TLUL_FILELIST := $(OPENTITAN_TLUL_RTL_DIR)filelist.f
OPENTITAN_TLUL_FRAGMENT_01_PKG := $(OPENTITAN_TLUL_RTL_DIR)fragments/01_pkg.f
OPENTITAN_TLUL_FRAGMENT_02_INTEGRITY := $(OPENTITAN_TLUL_RTL_DIR)fragments/02_integrity.f
OPENTITAN_TLUL_FRAGMENT_03_FIFO_ASSERT := $(OPENTITAN_TLUL_RTL_DIR)fragments/03_fifo_assert.f
OPENTITAN_TLUL_FRAGMENT_04_ADAPTERS := $(OPENTITAN_TLUL_RTL_DIR)fragments/04_adapters.f
OPENTITAN_TLUL_FRAGMENT_05_RACL := $(OPENTITAN_TLUL_RTL_DIR)fragments/05_racl.f
OPENTITAN_TLUL_FRAGMENT_06_DEBUG := $(OPENTITAN_TLUL_RTL_DIR)fragments/06_debug.f
OPENTITAN_TLUL_FRAGMENT_07_OPTIONAL_VH := $(OPENTITAN_TLUL_RTL_DIR)fragments/07_optional_vh.f

ifneq ($(OPENTITAN_TLUL_NO_AUTO_REGISTER),1)
ifeq (,$(filter $(OPENTITAN_TLUL_FILELIST),$(MODULE_FILELISTS)))
  MODULE_FILELISTS += $(OPENTITAN_TLUL_FILELIST)
endif
endif

endif
