/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 11.0.3 -fPIC -Os) */

(* top =  1  *)
(* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:1" *)
module rstn_test_mux(rst_n, test_rst_n, test_mode, rst_n_out);
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:2" *)
  input rst_n;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:5" *)
  output rst_n_out;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:4" *)
  input test_mode;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:3" *)
  input test_rst_n;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:8|/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v:5" *)
  wire \u_mux.a ;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:8|/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v:6" *)
  wire \u_mux.b ;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:8|/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v:4" *)
  wire \u_mux.sel ;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:8|/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v:7" *)
  wire \u_mux.y ;
  assign rst_n_out = test_mode ? (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rstn_test_mux.v:8|/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/std_cell/std_cell_mux.v:10" *) test_rst_n : rst_n;
  assign \u_mux.a  = rst_n;
  assign \u_mux.b  = test_rst_n;
  assign \u_mux.sel  = test_mode;
  assign \u_mux.y  = rst_n_out;
endmodule
