/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 11.0.3 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:10" *)
module rst_synchronizer(clk, rst_async_n, rst_sync_n);
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:14" *)
  input clk;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:15" *)
  input rst_async_n;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:16" *)
  output rst_sync_n;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:33" *)
  reg [1:0] sync_chain;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:36" *)
  always @(posedge clk or negedge rst_async_n)
    if (!rst_async_n)
      sync_chain[0] <= 0;
    else
      sync_chain[0] <= 1'h1;
  (* src = "/Users/ninghechuan/vibe_soc/ip/digital/soc_ip_common/de/rtl/rst_gen/rst_synchronizer.v:47" *)
  always @(posedge clk or negedge rst_async_n)
    if (!rst_async_n)
      sync_chain[1] <= 0;
    else
      sync_chain[1] <= sync_chain[0];
  assign rst_sync_n = sync_chain[1];
endmodule
