// opentitan_aes non-package RTL/model filelist
// Package sources are kept separately in pkg.f.

$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_reg_top.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ctrl_reg_shadowed.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ctrl_gcm_reg_shadowed.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_core.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ctr.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ctr_fsm.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ctr_fsm_p.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ctr_fsm_n.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_control.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_control_fsm.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_control_fsm_p.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_control_fsm_n.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_reg_status.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sel_buf_chk.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_cipher_core.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_cipher_control.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_cipher_control_fsm.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sub_bytes.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sbox.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sbox_lut.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sbox_canright.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sbox_canright_masked.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_sbox_dom.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_shift_rows.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_mix_columns.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_mix_single_column.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_key_expand.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_prng_clearing.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_prng_masking.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes_ghash.sv
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/rtl/aes.sv
+incdir+$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/model
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/model/crypto.c
$SOC/ip/digital/aes/de/rtl/src/hw/ip/aes/model/aes.c
